export interface CareerPathPlayer {
  name: string;
  clubs: string[]; // karriera në rend kronologjik (max 5 klube kryesore)
  nationality: string;
}

export const CAREER_PATH_PLAYERS: CareerPathPlayer[] = [
  // ── LEGJENDA ──
  { name: 'Zinedine Zidane',     clubs: ['Cannes', 'Bordeaux', 'Juventus', 'Real Madrid'],                       nationality: 'French' },
  { name: 'Ronaldo Nazário',     clubs: ['Cruzeiro', 'PSV', 'Barcelona', 'Inter Milan', 'Real Madrid'],          nationality: 'Brazilian' },
  { name: 'Ronaldinho',          clubs: ['Grêmio', 'PSG', 'Barcelona', 'AC Milan', 'Flamengo'],                  nationality: 'Brazilian' },
  { name: 'Thierry Henry',       clubs: ['Monaco', 'Juventus', 'Arsenal', 'Barcelona', 'New York RB'],           nationality: 'French' },
  { name: 'Roberto Carlos',      clubs: ['União São João', 'Palmeiras', 'Inter Milan', 'Real Madrid', 'Fenerbahçe'], nationality: 'Brazilian' },
  { name: 'Cafu',                clubs: ['São Paulo', 'Zaragoza', 'Roma', 'AC Milan'],                            nationality: 'Brazilian' },
  { name: 'Pavel Nedvěd',        clubs: ['Dukla Prague', 'Sparta Prague', 'Lazio', 'Juventus'],                   nationality: 'Czech' },
  { name: 'Michael Ballack',     clubs: ['Chemnitzer', 'Kaiserslautern', 'Bayer Leverkusen', 'Bayern Munich', 'Chelsea'], nationality: 'German' },
  { name: 'Andrés Iniesta',      clubs: ['Barcelona', 'Vissel Kobe'],                                             nationality: 'Spanish' },
  { name: 'Xavi Hernández',      clubs: ['Barcelona', 'Al Sadd'],                                                 nationality: 'Spanish' },
  { name: 'Zlatan Ibrahimović',  clubs: ['Malmö', 'Ajax', 'Juventus', 'Inter Milan', 'Barcelona', 'AC Milan', 'PSG', 'Manchester United'], nationality: 'Swedish' },
  { name: 'Didier Drogba',       clubs: ['Le Mans', 'Gueugnon', 'Marseille', 'Chelsea', 'Shanghai Shenhua'],     nationality: 'Ivorian' },
  { name: 'Frank Lampard',       clubs: ['West Ham', 'Chelsea', 'Manchester City', 'New York City'],              nationality: 'English' },
  { name: 'Steven Gerrard',      clubs: ['Liverpool', 'LA Galaxy'],                                               nationality: 'English' },
  { name: 'John Terry',          clubs: ['Chelsea', 'Aston Villa'],                                               nationality: 'English' },
  { name: 'Patrick Vieira',      clubs: ['Cannes', 'AC Milan', 'Arsenal', 'Juventus', 'Inter Milan', 'Manchester City'], nationality: 'French' },
  { name: 'Gianluigi Buffon',    clubs: ['Parma', 'Juventus', 'PSG'],                                            nationality: 'Italian' },
  { name: 'Paolo Maldini',       clubs: ['AC Milan'],                                                             nationality: 'Italian' },
  { name: 'Alessandro Del Piero',clubs: ['Padova', 'Juventus', 'Sydney FC'],                                     nationality: 'Italian' },
  { name: 'Francesco Totti',     clubs: ['Roma'],                                                                 nationality: 'Italian' },
  { name: 'Andrea Pirlo',        clubs: ['Brescia', 'Inter Milan', 'AC Milan', 'Juventus', 'New York City'],     nationality: 'Italian' },
  { name: 'Filippo Inzaghi',     clubs: ['Juventus', 'AC Milan'],                                                 nationality: 'Italian' },
  { name: 'Hernan Crespo',       clubs: ['River Plate', 'Parma', 'Lazio', 'Inter Milan', 'Chelsea', 'AC Milan'], nationality: 'Argentinian' },
  { name: 'Juan Sebastián Verón',clubs: ['Estudiantes', 'Sampdoria', 'Parma', 'Lazio', 'Manchester United', 'Chelsea'], nationality: 'Argentinian' },
  { name: 'Gabriel Batistuta',   clubs: ['Boca Juniors', 'Fiorentina', 'Roma', 'Inter Milan'],                   nationality: 'Argentinian' },
  { name: 'Rivaldo',             clubs: ['Palmeiras', 'Deportivo', 'Barcelona', 'AC Milan', 'Cruzeiro'],         nationality: 'Brazilian' },
  { name: 'Romário',             clubs: ['Vasco', 'PSV', 'Barcelona', 'Valencia', 'Flamengo'],                   nationality: 'Brazilian' },
  { name: 'Bebeto',              clubs: ['Flamengo', 'Vasco', 'Deportivo', 'Sevilla'],                            nationality: 'Brazilian' },
  { name: 'Roberto Baggio',      clubs: ['Fiorentina', 'Juventus', 'AC Milan', 'Bologna', 'Brescia'],            nationality: 'Italian' },
  { name: 'George Weah',         clubs: ['Monaco', 'PSG', 'AC Milan', 'Chelsea', 'Manchester City'],             nationality: 'Liberian' },
  { name: 'David Beckham',       clubs: ['Manchester United', 'Real Madrid', 'LA Galaxy', 'AC Milan', 'PSG'],    nationality: 'English' },
  { name: 'Raúl',                clubs: ['Atlético Madrid', 'Real Madrid', 'Schalke', 'Al Sadd'],                nationality: 'Spanish' },
  { name: 'Luís Figo',           clubs: ['Sporting CP', 'Barcelona', 'Real Madrid', 'Inter Milan'],              nationality: 'Portuguese' },
  { name: 'Emerson',             clubs: ['Bayer Leverkusen', 'Roma', 'Juventus', 'Real Madrid', 'AC Milan'],     nationality: 'Brazilian' },
  { name: 'Edgar Davids',        clubs: ['Ajax', 'AC Milan', 'Juventus', 'Barcelona', 'Inter Milan', 'Tottenham'], nationality: 'Dutch' },
  { name: 'Clarence Seedorf',    clubs: ['Ajax', 'Sampdoria', 'Real Madrid', 'Inter Milan', 'AC Milan'],         nationality: 'Dutch' },
  { name: 'Patrick Kluivert',    clubs: ['Ajax', 'AC Milan', 'Barcelona', 'Newcastle', 'Valencia'],              nationality: 'Dutch' },
  { name: 'Marc Overmars',       clubs: ['Ajax', 'Arsenal', 'Barcelona'],                                         nationality: 'Dutch' },
  { name: 'Dennis Bergkamp',     clubs: ['Ajax', 'Inter Milan', 'Arsenal'],                                       nationality: 'Dutch' },
  { name: 'Ruud van Nistelrooy', clubs: ['Den Bosch', 'Heerenveen', 'PSV', 'Manchester United', 'Real Madrid', 'Hamburg'], nationality: 'Dutch' },
  { name: 'Arjen Robben',        clubs: ['Groningen', 'PSV', 'Chelsea', 'Real Madrid', 'Bayern Munich'],         nationality: 'Dutch' },
  { name: 'Dirk Kuyt',           clubs: ['FC Utrecht', 'Feyenoord', 'Liverpool', 'Fenerbahçe'],                  nationality: 'Dutch' },
  { name: 'Wesley Sneijder',     clubs: ['Ajax', 'Real Madrid', 'Inter Milan', 'Galatasaray'],                    nationality: 'Dutch' },
  { name: 'Robin van Persie',    clubs: ['Feyenoord', 'Arsenal', 'Manchester United', 'Fenerbahçe'],             nationality: 'Dutch' },
  { name: 'Roy Keane',           clubs: ['Nottingham Forest', 'Manchester United', 'Celtic'],                     nationality: 'Irish' },
  { name: 'Peter Schmeichel',    clubs: ['Brøndby', 'Manchester United', 'Sporting CP', 'Aston Villa', 'Manchester City'], nationality: 'Danish' },
  { name: 'Ole Gunnar Solskjær', clubs: ['Molde', 'Manchester United'],                                           nationality: 'Norwegian' },
  { name: 'Dwight Yorke',        clubs: ['Aston Villa', 'Manchester United', 'Blackburn', 'Birmingham'],         nationality: 'Trinidadian' },
  { name: 'Andy Cole',           clubs: ['Newcastle', 'Manchester United', 'Blackburn', 'Fulham'],               nationality: 'English' },
  { name: 'Alan Shearer',        clubs: ['Southampton', 'Blackburn', 'Newcastle'],                                nationality: 'English' },
  { name: 'Paul Scholes',        clubs: ['Manchester United'],                                                    nationality: 'English' },

  // ── GJENERATA 2000-2010 ──
  { name: 'Kaká',                clubs: ['São Paulo', 'AC Milan', 'Real Madrid', 'Orlando City'],                 nationality: 'Brazilian' },
  { name: 'Samuel Eto\'o',       clubs: ['Real Madrid', 'Mallorca', 'Barcelona', 'Inter Milan', 'Chelsea'],      nationality: 'Cameroonian' },
  { name: 'Deco',                clubs: ['FC Porto', 'Barcelona', 'Chelsea'],                                     nationality: 'Portuguese' },
  { name: 'Ashley Cole',         clubs: ['Arsenal', 'Chelsea', 'Roma', 'LA Galaxy'],                             nationality: 'English' },
  { name: 'Claude Makélélé',     clubs: ['Nantes', 'Marseille', 'Celta Vigo', 'Real Madrid', 'Chelsea', 'PSG'], nationality: 'French' },
  { name: 'Nicolas Anelka',      clubs: ['Arsenal', 'Real Madrid', 'PSG', 'Manchester City', 'Bolton', 'Chelsea', 'Shanghai'], nationality: 'French' },
  { name: 'Robert Pires',        clubs: ['Metz', 'Marseille', 'Arsenal', 'Villarreal'],                          nationality: 'French' },
  { name: 'Sylvain Wiltord',     clubs: ['Bordeaux', 'Arsenal', 'Lyon'],                                          nationality: 'French' },
  { name: 'David Trezeguet',     clubs: ['Monaco', 'Juventus', 'Hercules'],                                       nationality: 'French' },
  { name: 'Lilian Thuram',       clubs: ['Monaco', 'Parma', 'Juventus', 'Barcelona'],                            nationality: 'French' },
  { name: 'Marcel Desailly',     clubs: ['Nantes', 'Marseille', 'AC Milan', 'Chelsea', 'Al-Gharafa'],            nationality: 'French' },
  { name: 'Emmanuel Petit',      clubs: ['Monaco', 'Arsenal', 'Barcelona', 'Chelsea'],                            nationality: 'French' },
  { name: 'Youri Djorkaeff',     clubs: ['Monaco', 'PSG', 'Inter Milan', 'Lazio', 'Kaiserslautern'],             nationality: 'French' },
  { name: 'Robinho',             clubs: ['Santos', 'Real Madrid', 'Manchester City', 'AC Milan'],                 nationality: 'Brazilian' },
  { name: 'Adriano',             clubs: ['Inter Milan', 'Fiorentina', 'Parma', 'Roma'],                          nationality: 'Brazilian' },
  { name: 'Diego',               clubs: ['Porto', 'Werder Bremen', 'Atletico Madrid', 'Juventus'],               nationality: 'Brazilian' },
  { name: 'Julio Baptista',      clubs: ['Sevilla', 'Real Madrid', 'Arsenal', 'Roma'],                           nationality: 'Brazilian' },
  { name: 'Grafite',             clubs: ['São Paulo', 'Wolfsburg', 'Anzhi'],                                      nationality: 'Brazilian' },
  { name: 'Edin Džeko',          clubs: ['Željezničar', 'Wolfsburg', 'Manchester City', 'Roma', 'Inter Milan'],  nationality: 'Bosnian' },
  { name: 'Miroslav Klose',      clubs: ['Kaiserslautern', 'Werder Bremen', 'Bayern Munich', 'Lazio'],           nationality: 'German' },
  { name: 'Lukas Podolski',      clubs: ['Köln', 'Bayern Munich', 'Arsenal', 'Galatasaray', 'Inter Milan'],      nationality: 'German' },
  { name: 'Bastian Schweinsteiger', clubs: ['Bayern Munich', 'Manchester United', 'Chicago Fire'],               nationality: 'German' },
  { name: 'Oliver Kahn',         clubs: ['Karlsruhe', 'Bayern Munich'],                                           nationality: 'German' },
  { name: 'Jens Lehmann',        clubs: ['Schalke', 'AC Milan', 'Borussia Dortmund', 'Arsenal', 'Stuttgart'],    nationality: 'German' },
  { name: 'Philipp Lahm',        clubs: ['Bayern Munich', 'Stuttgart'],                                           nationality: 'German' },
  { name: 'Per Mertesacker',     clubs: ['Hannover', 'Werder Bremen', 'Arsenal'],                                 nationality: 'German' },
  { name: 'Carles Puyol',        clubs: ['Barcelona'],                                                            nationality: 'Spanish' },
  { name: 'Sergio Ramos',        clubs: ['Sevilla', 'Real Madrid', 'PSG'],                                        nationality: 'Spanish' },
  { name: 'Fernando Torres',     clubs: ['Atletico Madrid', 'Liverpool', 'Chelsea', 'AC Milan', 'Atletico Madrid'], nationality: 'Spanish' },
  { name: 'David Villa',         clubs: ['Sporting de Gijón', 'Zaragoza', 'Valencia', 'Barcelona', 'Atletico Madrid', 'New York City'], nationality: 'Spanish' },
  { name: 'Cesc Fàbregas',       clubs: ['Arsenal', 'Barcelona', 'Chelsea', 'Monaco'],                           nationality: 'Spanish' },
  { name: 'Fernando Morientes',  clubs: ['Real Madrid', 'Monaco', 'Liverpool', 'Valencia', 'Marseille'],         nationality: 'Spanish' },
  { name: 'Iker Casillas',       clubs: ['Real Madrid', 'Porto'],                                                 nationality: 'Spanish' },
  { name: 'Álvaro Arbeloa',      clubs: ['Real Madrid', 'Deportivo', 'Liverpool', 'Real Madrid'],                nationality: 'Spanish' },
  { name: 'Joaquín',             clubs: ['Betis', 'Valencia', 'Málaga', 'Fiorentina', 'Betis'],                  nationality: 'Spanish' },

  // ── GJENERATA 2010-2020 ──
  { name: 'Lionel Messi',        clubs: ['Barcelona', 'PSG', 'Inter Miami'],                                     nationality: 'Argentinian' },
  { name: 'Cristiano Ronaldo',   clubs: ['Sporting CP', 'Manchester United', 'Real Madrid', 'Juventus', 'Manchester United', 'Al Nassr'], nationality: 'Portuguese' },
  { name: 'Neymar Jr',           clubs: ['Santos', 'Barcelona', 'PSG', 'Al Hilal'],                              nationality: 'Brazilian' },
  { name: 'Gareth Bale',         clubs: ['Southampton', 'Tottenham', 'Real Madrid', 'LAFC'],                     nationality: 'Welsh' },
  { name: 'Ángel Di María',      clubs: ['Benfica', 'Real Madrid', 'Manchester United', 'PSG', 'Juventus', 'Benfica'], nationality: 'Argentinian' },
  { name: 'Gonzalo Higuaín',     clubs: ['River Plate', 'Real Madrid', 'Napoli', 'Juventus', 'Chelsea', 'AC Milan'], nationality: 'Argentinian' },
  { name: 'Sergio Agüero',       clubs: ['Independiente', 'Atletico Madrid', 'Manchester City', 'Barcelona'],    nationality: 'Argentinian' },
  { name: 'Carlos Tevez',        clubs: ['Corinthians', 'West Ham', 'Manchester United', 'Manchester City', 'Juventus', 'Boca Juniors'], nationality: 'Argentinian' },
  { name: 'Javier Mascherano',   clubs: ['River Plate', 'Corinthians', 'Liverpool', 'Barcelona', 'Hebei China Fortune'], nationality: 'Argentinian' },
  { name: 'Pablo Aimar',         clubs: ['River Plate', 'Valencia', 'Zaragoza', 'Benfica'],                      nationality: 'Argentinian' },
  { name: 'Juan Román Riquelme', clubs: ['Boca Juniors', 'Barcelona', 'Villarreal'],                              nationality: 'Argentinian' },
  { name: 'Sergio Busquets',     clubs: ['Barcelona', 'Inter Miami'],                                             nationality: 'Spanish' },
  { name: 'Jordi Alba',          clubs: ['Valencia', 'Barcelona', 'Inter Miami'],                                 nationality: 'Spanish' },
  { name: 'Gerard Piqué',        clubs: ['Barcelona', 'Manchester United'],                                       nationality: 'Spanish' },
  { name: 'Diego Costa',         clubs: ['Atletico Madrid', 'Chelsea', 'Atletico Madrid'],                        nationality: 'Spanish' },
  { name: 'Álvaro Morata',       clubs: ['Real Madrid', 'Juventus', 'Chelsea', 'Atletico Madrid', 'Juventus'],   nationality: 'Spanish' },
  { name: 'Santi Cazorla',       clubs: ['Villarreal', 'Málaga', 'Arsenal', 'Villarreal'],                       nationality: 'Spanish' },
  { name: 'Nacho Monreal',       clubs: ['Osasuna', 'Málaga', 'Arsenal', 'Real Sociedad'],                       nationality: 'Spanish' },
  { name: 'Juan Mata',           clubs: ['Valencia', 'Chelsea', 'Manchester United'],                             nationality: 'Spanish' },
  { name: 'David de Gea',        clubs: ['Atletico Madrid', 'Manchester United'],                                  nationality: 'Spanish' },
  { name: 'Eden Hazard',         clubs: ['Lille', 'Chelsea', 'Real Madrid'],                                      nationality: 'Belgian' },
  { name: 'Romelu Lukaku',       clubs: ['Anderlecht', 'Chelsea', 'Everton', 'Manchester United', 'Inter Milan', 'Chelsea', 'Inter Milan'], nationality: 'Belgian' },
  { name: 'Dries Mertens',       clubs: ['STVV', 'Gent', 'PSV', 'Napoli', 'Galatasaray'],                       nationality: 'Belgian' },
  { name: 'Vincent Kompany',     clubs: ['Anderlecht', 'Hamburg', 'Manchester City', 'Burnley'],                  nationality: 'Belgian' },
  { name: 'Axel Witsel',         clubs: ['Standard Liège', 'Benfica', 'Zenit', 'Juventus', 'Borussia Dortmund', 'Atletico Madrid'], nationality: 'Belgian' },
  { name: 'Thomas Vermaelen',    clubs: ['Ajax', 'Arsenal', 'Barcelona', 'Roma'],                                 nationality: 'Belgian' },
  { name: 'Laurent Ciman',       clubs: ['Anderlecht', 'Standard Liège', 'Club Brugge', 'Lille', 'Montreal'],   nationality: 'Belgian' },
  { name: 'Mario Balotelli',     clubs: ['Inter Milan', 'Manchester City', 'AC Milan', 'Liverpool', 'Nice'],     nationality: 'Italian' },
  { name: 'Antonio Cassano',     clubs: ['Roma', 'Real Madrid', 'Sampdoria', 'AC Milan', 'Inter Milan'],         nationality: 'Italian' },
  { name: 'Gennaro Gattuso',     clubs: ['Rangers', 'Salernitana', 'AC Milan'],                                   nationality: 'Italian' },
  { name: 'Daniele De Rossi',    clubs: ['Roma', 'Boca Juniors'],                                                  nationality: 'Italian' },
  { name: 'Giorgio Chiellini',   clubs: ['Livorno', 'Fiorentina', 'Juventus', 'LAFC'],                           nationality: 'Italian' },
  { name: 'Leonardo Bonucci',    clubs: ['Juventus', 'AC Milan', 'Juventus'],                                      nationality: 'Italian' },
  { name: 'Marco Verratti',      clubs: ['Pescara', 'PSG', 'Al-Arabi'],                                           nationality: 'Italian' },
  { name: 'Ciro Immobile',       clubs: ['Juventus', 'Genoa', 'Torino', 'Dortmund', 'Sevilla', 'Lazio'],         nationality: 'Italian' },
  { name: 'Lorenzo Insigne',     clubs: ['Napoli', 'Toronto FC'],                                                  nationality: 'Italian' },
  { name: 'Paulo Dybala',        clubs: ['Instituto', 'Palermo', 'Juventus', 'Roma'],                             nationality: 'Argentinian' },
  { name: 'Lautaro Martínez',    clubs: ['Racing Club', 'Inter Milan'],                                            nationality: 'Argentinian' },
  { name: 'Mauro Icardi',        clubs: ['Sampdoria', 'Inter Milan', 'PSG'],                                      nationality: 'Argentinian' },
  { name: 'Ever Banega',         clubs: ['Boca Juniors', 'Valencia', 'Atletico Madrid', 'Inter Milan', 'Sevilla', 'Al Shabab'], nationality: 'Argentinian' },
  { name: 'Erik Lamela',         clubs: ['River Plate', 'Roma', 'Tottenham', 'Sevilla'],                          nationality: 'Argentinian' },
  { name: 'James Rodríguez',     clubs: ['Envigado', 'Banfield', 'Porto', 'Monaco', 'Real Madrid', 'Bayern Munich', 'Everton'], nationality: 'Colombian' },
  { name: 'Radamel Falcao',      clubs: ['River Plate', 'Porto', 'Atletico Madrid', 'Monaco', 'Manchester United', 'Chelsea'], nationality: 'Colombian' },
  { name: 'Juan Cuadrado',       clubs: ['Udinese', 'Fiorentina', 'Chelsea', 'Juventus', 'Inter Milan'],         nationality: 'Colombian' },
  { name: 'David Ospina',        clubs: ['Nacional', 'Nice', 'Arsenal', 'Napoli', 'Al Qadsiah'],                 nationality: 'Colombian' },
  { name: 'Luis Suárez',         clubs: ['Nacional', 'Groningen', 'Ajax', 'Liverpool', 'Barcelona', 'Atletico Madrid', 'Nacional'], nationality: 'Uruguayan' },
  { name: 'Edinson Cavani',      clubs: ['Danubio', 'Palermo', 'Napoli', 'PSG', 'Manchester United', 'Valencia'], nationality: 'Uruguayan' },
  { name: 'Diego Forlán',        clubs: ['Independiente', 'Manchester United', 'Villarreal', 'Atletico Madrid', 'Inter Milan'], nationality: 'Uruguayan' },
  { name: 'Diego Lugano',        clubs: ['Nacional', 'São Paulo', 'Fenerbahçe', 'Málaga', 'West Brom'],          nationality: 'Uruguayan' },
  { name: 'Christian Benteke',   clubs: ['Genk', 'Standard Liège', 'Aston Villa', 'Liverpool', 'Crystal Palace'], nationality: 'Belgian' },
  { name: 'Mesut Özil',          clubs: ['Schalke', 'Werder Bremen', 'Real Madrid', 'Arsenal', 'Fenerbahçe'],    nationality: 'German' },
  { name: 'Mario Götze',         clubs: ['Borussia Dortmund', 'Bayern Munich', 'PSV', 'Eintracht Frankfurt'],    nationality: 'German' },
  { name: 'Marco Reus',          clubs: ['Borussia Dortmund'],                                                    nationality: 'German' },
  { name: 'Thomas Müller',       clubs: ['Bayern Munich'],                                                        nationality: 'German' },
  { name: 'Toni Kroos',          clubs: ['Bayern Munich', 'Bayer Leverkusen', 'Bayern Munich', 'Real Madrid'],   nationality: 'German' },
  { name: 'Sami Khedira',        clubs: ['Stuttgart', 'Real Madrid', 'Juventus', 'Arsenal'],                      nationality: 'German' },
  { name: 'Mats Hummels',        clubs: ['Bayern Munich', 'Borussia Dortmund', 'Bayern Munich', 'Borussia Dortmund'], nationality: 'German' },
  { name: 'Jerome Boateng',      clubs: ['Hertha Berlin', 'Hamburg', 'Manchester City', 'Bayern Munich', 'Lyon'], nationality: 'German' },
  { name: 'Shkodran Mustafi',    clubs: ['Everton', 'Sampdoria', 'Valencia', 'Arsenal', 'Schalke'],              nationality: 'German' },
  { name: 'André Schürrle',      clubs: ['Mainz', 'Bayer Leverkusen', 'Chelsea', 'Wolfsburg', 'Borussia Dortmund'], nationality: 'German' },
  { name: 'Julian Draxler',      clubs: ['Schalke', 'Wolfsburg', 'PSG', 'Benfica'],                              nationality: 'German' },
  { name: 'Leroy Sané',          clubs: ['Schalke', 'Manchester City', 'Bayern Munich'],                          nationality: 'German' },
  { name: 'Serge Gnabry',        clubs: ['Arsenal', 'West Brom', 'Werder Bremen', 'Hoffenheim', 'Bayern Munich'], nationality: 'German' },
  { name: 'Ilkay Gündogan',      clubs: ['Nürnberg', 'Borussia Dortmund', 'Manchester City', 'Barcelona', 'Manchester City'], nationality: 'German' },
  { name: 'Leon Goretzka',       clubs: ['Schalke', 'Bayern Munich'],                                             nationality: 'German' },
  { name: 'Kai Havertz',         clubs: ['Bayer Leverkusen', 'Chelsea', 'Arsenal'],                              nationality: 'German' },
  { name: 'Granit Xhaka',        clubs: ['Basel', 'Borussia Mönchengladbach', 'Arsenal', 'Bayer Leverkusen'],    nationality: 'Swiss' },
  { name: 'Xherdan Shaqiri',     clubs: ['Basel', 'Bayern Munich', 'Inter Milan', 'Stoke', 'Liverpool', 'Lyon', 'Chicago Fire'], nationality: 'Swiss' },
  { name: 'Stephan Lichtsteiner',clubs: ['Lazio', 'Juventus', 'Arsenal'],                                         nationality: 'Swiss' },
  { name: 'Yann Sommer',         clubs: ['Basel', 'Borussia Mönchengladbach', 'Bayern Munich', 'Inter Milan'],   nationality: 'Swiss' },
  { name: 'Ricardo Rodríguez',   clubs: ['Wolfsburg', 'AC Milan', 'Torino'],                                      nationality: 'Swiss' },
  { name: 'Hakan Çalhanoğlu',    clubs: ['Hamburg', 'Bayer Leverkusen', 'AC Milan', 'Inter Milan'],              nationality: 'Turkish' },
  { name: 'Arda Turan',          clubs: ['Galatasaray', 'Atletico Madrid', 'Barcelona', 'Basaksehir'],            nationality: 'Turkish' },
  { name: 'Burak Yılmaz',        clubs: ['Trabzonspor', 'Galatasaray', 'Beijing Guoan', 'Lille'],                nationality: 'Turkish' },
  { name: 'Dimitar Berbatov',    clubs: ['CSKA Sofia', 'Bayer Leverkusen', 'Tottenham', 'Manchester United', 'Fulham', 'Monaco'], nationality: 'Bulgarian' },
  { name: 'Martin Škrtel',       clubs: ['Trenčín', 'Zenit', 'Liverpool', 'Fenerbahçe', 'Atalanta'],             nationality: 'Slovak' },
  { name: 'Marek Hamšík',        clubs: ['Slovan Bratislava', 'Brescia', 'Napoli', 'Dalian Professional'],       nationality: 'Slovak' },
  { name: 'Robert Vittek',       clubs: ['Slovan Bratislava', 'Lille', 'Nürnberg', 'Vitesse'],                   nationality: 'Slovak' },
  { name: 'Luka Modrić',         clubs: ['Dinamo Zagreb', 'Tottenham', 'Real Madrid'],                            nationality: 'Croatian' },
  { name: 'Ivan Rakitić',        clubs: ['Basel', 'Schalke', 'Sevilla', 'Barcelona', 'Sevilla'],                 nationality: 'Croatian' },
  { name: 'Mario Mandžukić',     clubs: ['Dinamo Zagreb', 'Wolfsburg', 'Bayern Munich', 'Atletico Madrid', 'Juventus', 'AC Milan'], nationality: 'Croatian' },
  { name: 'Darijo Srna',         clubs: ['Hajduk Split', 'Shakhtar', 'Cagliari'],                                 nationality: 'Croatian' },
  { name: 'Vedran Ćorluka',      clubs: ['Dinamo Zagreb', 'Manchester City', 'Tottenham', 'Lokomotiv Moscow'],   nationality: 'Croatian' },
  { name: 'Nikica Jelavić',      clubs: ['Dinamo Zagreb', 'Rapid Vienna', 'Rangers', 'Everton'],                 nationality: 'Croatian' },
  { name: 'Dejan Lovren',        clubs: ['Dinamo Zagreb', 'Lyon', 'Southampton', 'Liverpool', 'Zenit'],          nationality: 'Croatian' },
  { name: 'Mateo Kovačić',       clubs: ['Dinamo Zagreb', 'Inter Milan', 'Real Madrid', 'Chelsea'],              nationality: 'Croatian' },
  { name: 'Ivan Perišić',        clubs: ['Sochaux', 'Club Brugge', 'Borussia Dortmund', 'Wolfsburg', 'Inter Milan', 'Bayern Munich', 'Tottenham'], nationality: 'Croatian' },
  { name: 'Marcelo Brozović',    clubs: ['Dinamo Zagreb', 'Lokomotiv Zagreb', 'Inter Milan', 'Al Nassr'],        nationality: 'Croatian' },
  { name: 'Ante Rebić',          clubs: ['Fiorentina', 'Eintracht Frankfurt', 'AC Milan'],                        nationality: 'Croatian' },
  { name: 'Bruno Petković',      clubs: ['Rijeka', 'Dinamo Zagreb', 'Atalanta', 'Bologna'],                      nationality: 'Croatian' },

  // ── YJET AKTUALË ──
  { name: 'Kylian Mbappé',       clubs: ['Monaco', 'PSG', 'Real Madrid'],                                        nationality: 'French' },
  { name: 'Antoine Griezmann',   clubs: ['Real Sociedad', 'Atletico Madrid', 'Barcelona', 'Atletico Madrid'],    nationality: 'French' },
  { name: 'Paul Pogba',          clubs: ['Manchester United', 'Juventus', 'Manchester United', 'Juventus'],       nationality: 'French' },
  { name: 'N\'Golo Kanté',       clubs: ['Boulogne', 'Caen', 'Leicester', 'Chelsea', 'Al Ittihad'],              nationality: 'French' },
  { name: 'Raphaël Varane',      clubs: ['Lens', 'Real Madrid', 'Manchester United', 'Como'],                     nationality: 'French' },
  { name: 'Benjamin Pavard',     clubs: ['Stuttgart', 'Bayern Munich', 'Inter Milan'],                            nationality: 'French' },
  { name: 'Ousmane Dembélé',     clubs: ['Rennes', 'Borussia Dortmund', 'Barcelona', 'PSG'],                     nationality: 'French' },
  { name: 'Olivier Giroud',      clubs: ['Tours', 'Montpellier', 'Arsenal', 'Chelsea', 'AC Milan', 'LAFC'],      nationality: 'French' },
  { name: 'Karim Benzema',       clubs: ['Lyon', 'Real Madrid', 'Al Ittihad'],                                    nationality: 'French' },
  { name: 'Franck Ribéry',       clubs: ['Boulogne', 'Ales', 'Brest', 'Metz', 'Galatasaray', 'Marseille', 'Bayern Munich', 'Fiorentina'], nationality: 'French' },
  { name: 'Mamadou Sakho',       clubs: ['PSG', 'Liverpool', 'Crystal Palace', 'Montpellier'],                   nationality: 'French' },
  { name: 'Hugo Lloris',         clubs: ['Nice', 'Lyon', 'Tottenham', 'LA Galaxy'],                              nationality: 'French' },
  { name: 'Steve Mandanda',      clubs: ['Le Havre', 'Marseille', 'Crystal Palace'],                              nationality: 'French' },
  { name: 'Bacary Sagna',        clubs: ['Sens', 'Auxerre', 'Arsenal', 'Manchester City', 'Benevento'],          nationality: 'French' },
  { name: 'Moussa Sissoko',      clubs: ['Toulouse', 'Newcastle', 'Tottenham', 'Watford', 'Nantes'],             nationality: 'French' },
  { name: 'Blaise Matuidi',      clubs: ['Troyes', 'Saint-Étienne', 'PSG', 'Juventus', 'Inter Miami'],           nationality: 'French' },
  { name: 'Adrien Rabiot',       clubs: ['PSG', 'Juventus', 'Manchester United', 'Marseille'],                    nationality: 'French' },
  { name: 'Marcus Rashford',     clubs: ['Manchester United'],                                                    nationality: 'English' },
  { name: 'Harry Kane',          clubs: ['Tottenham', 'Millwall', 'Leicester', 'Norwich', 'Aston Villa', 'Bayern Munich'], nationality: 'English' },
  { name: 'Raheem Sterling',     clubs: ['Liverpool', 'Manchester City', 'Chelsea', 'Arsenal'],                   nationality: 'English' },
  { name: 'Jordan Henderson',    clubs: ['Sunderland', 'Coventry', 'Liverpool', 'Al Ettifaq', 'Ajax'],           nationality: 'English' },
  { name: 'Joe Hart',            clubs: ['Manchester City', 'Burnley', 'Tottenham', 'Celtic'],                    nationality: 'English' },
  { name: 'James Milner',        clubs: ['Leeds', 'Newcastle', 'Aston Villa', 'Manchester City', 'Liverpool', 'Brighton'], nationality: 'English' },
  { name: 'Danny Welbeck',       clubs: ['Manchester United', 'Sunderland', 'Preston', 'Arsenal', 'Watford', 'Brighton'], nationality: 'English' },
  { name: 'Wayne Rooney',        clubs: ['Everton', 'Manchester United', 'Everton', 'DC United', 'Derby'],       nationality: 'English' },
  { name: 'Michael Owen',        clubs: ['Liverpool', 'Real Madrid', 'Newcastle', 'Manchester United', 'Stoke'], nationality: 'English' },
  { name: 'Rio Ferdinand',       clubs: ['West Ham', 'Leeds', 'Manchester United', 'QPR'],                        nationality: 'English' },
  { name: 'Gary Neville',        clubs: ['Manchester United'],                                                    nationality: 'English' },
  { name: 'Sol Campbell',        clubs: ['Tottenham', 'Arsenal', 'Portsmouth', 'Notts County'],                   nationality: 'English' },
  { name: 'Emile Heskey',        clubs: ['Leicester', 'Liverpool', 'Birmingham', 'Wigan', 'Aston Villa'],         nationality: 'English' },
  { name: 'Paul Ince',           clubs: ['West Ham', 'Manchester United', 'Inter Milan', 'Liverpool', 'Middlesbrough'], nationality: 'English' },
  { name: 'Dion Dublin',         clubs: ['Cambridge', 'Manchester United', 'Coventry', 'Aston Villa'],            nationality: 'English' },
  { name: 'Emerson Royal',       clubs: ['Real Betis', 'Barcelona', 'Tottenham', 'AC Milan'],                     nationality: 'Brazilian' },
  { name: 'Casemiro',            clubs: ['São Paulo', 'Real Madrid', 'Porto', 'Manchester United'],               nationality: 'Brazilian' },
  { name: 'Thiago Silva',        clubs: ['Fluminense', 'AC Milan', 'PSG', 'Chelsea'],                             nationality: 'Brazilian' },
  { name: 'Dani Alves',          clubs: ['Bahia', 'Sevilla', 'Barcelona', 'Juventus', 'PSG', 'São Paulo'],       nationality: 'Brazilian' },
  { name: 'Marquinhos',          clubs: ['Roma', 'PSG'],                                                           nationality: 'Brazilian' },
  { name: 'Willian',             clubs: ['Shakhtar', 'Anzhi', 'Chelsea', 'Arsenal', 'Corinthians'],              nationality: 'Brazilian' },
  { name: 'Oscar',               clubs: ['Internacional', 'Chelsea', 'Shanghai SIPG'],                            nationality: 'Brazilian' },
  { name: 'Philippe Coutinho',   clubs: ['Vasco', 'Inter Milan', 'Liverpool', 'Barcelona', 'Aston Villa'],        nationality: 'Brazilian' },
  { name: 'Gabriel Jesus',       clubs: ['Palmeiras', 'Manchester City', 'Arsenal'],                              nationality: 'Brazilian' },
  { name: 'Alex Sandro',         clubs: ['Porto', 'Juventus', 'Atletico Madrid'],                                  nationality: 'Brazilian' },
  { name: 'Hulk',                clubs: ['Vitória', 'Porto', 'Zenit', 'Shanghai SIPG', 'Atletico Mineiro'],      nationality: 'Brazilian' },
  { name: 'Douglas Costa',       clubs: ['Shakhtar', 'Bayern Munich', 'Juventus', 'Grêmio'],                     nationality: 'Brazilian' },
  { name: 'Allan',               clubs: ['Vasco', 'Udinese', 'Napoli', 'Everton', 'Marseille'],                  nationality: 'Brazilian' },
  { name: 'Fabinho',             clubs: ['Rio Ave', 'Monaco', 'Liverpool', 'Al Ittihad'],                         nationality: 'Brazilian' },
  { name: 'Fred',                clubs: ['Fluminense', 'Shakhtar', 'Manchester United', 'Fenerbahçe'],            nationality: 'Brazilian' },
  { name: 'Fernandinho',         clubs: ['Athletico Paranaense', 'Shakhtar', 'Manchester City', 'Athletico Paranaense'], nationality: 'Brazilian' },
  { name: 'David Luiz',          clubs: ['Vitória', 'Benfica', 'Chelsea', 'PSG', 'Arsenal'],                      nationality: 'Brazilian' },
  { name: 'Dante',               clubs: ['Borussia Mönchengladbach', 'Bayern Munich', 'Nice'],                    nationality: 'Brazilian' },
  { name: 'Pepe',                clubs: ['Marítimo', 'Porto', 'Real Madrid', 'Besiktas', 'Porto'],               nationality: 'Portuguese' },
  { name: 'Bruno Fernandes',     clubs: ['Novara', 'Udinese', 'Sampdoria', 'Sporting CP', 'Manchester United'],  nationality: 'Portuguese' },
  { name: 'Bernardo Silva',      clubs: ['Monaco', 'Manchester City'],                                            nationality: 'Portuguese' },
  { name: 'Rúben Dias',          clubs: ['Benfica', 'Manchester City'],                                            nationality: 'Portuguese' },
  { name: 'João Félix',          clubs: ['Benfica', 'Atletico Madrid', 'Chelsea', 'Barcelona', 'Atletico Madrid'], nationality: 'Portuguese' },
  { name: 'Diogo Jota',          clubs: ['Paços de Ferreira', 'Atletico Madrid', 'Porto', 'Wolverhampton', 'Liverpool'], nationality: 'Portuguese' },
  { name: 'Rúben Neves',         clubs: ['Porto', 'Wolverhampton', 'Al Hilal', 'Barcelona'],                     nationality: 'Portuguese' },
  { name: 'Gonçalo Guedes',      clubs: ['Benfica', 'PSG', 'Valencia', 'Wolves', 'Benfica'],                     nationality: 'Portuguese' },
  { name: 'Nelson Semedo',       clubs: ['Benfica', 'Barcelona', 'Wolverhampton'],                                 nationality: 'Portuguese' },
  { name: 'Renato Sanches',      clubs: ['Benfica', 'Bayern Munich', 'Swansea', 'Lille', 'PSG', 'Roma'],         nationality: 'Portuguese' },
  { name: 'Ricardo Quaresma',    clubs: ['Sporting CP', 'Barcelona', 'Porto', 'Inter Milan', 'Besiktas'],        nationality: 'Portuguese' },
  { name: 'Nani',                clubs: ['Sporting CP', 'Manchester United', 'Fenerbahçe', 'Lazio', 'Valencia'], nationality: 'Portuguese' },
  { name: 'Simão Sabrosa',       clubs: ['Sporting CP', 'Barcelona', 'Deportivo', 'Atlético Madrid', 'Benfica'], nationality: 'Portuguese' },
  { name: 'Hélder Postiga',      clubs: ['Porto', 'Tottenham', 'Porto', 'Zaragoza', 'Real Sociedad'],            nationality: 'Portuguese' },
  { name: 'Rui Costa',           clubs: ['Fiorentina', 'AC Milan', 'Benfica'],                                    nationality: 'Portuguese' },
  { name: 'Robert Pires',        clubs: ['Metz', 'Marseille', 'Arsenal', 'Villarreal'],                          nationality: 'French' },
  { name: 'Moussa Dembélé',      clubs: ['Fulham', 'Tottenham', 'Swansea', 'Leicester', 'Atlético Madrid'],      nationality: 'Belgian' },
  { name: 'Michy Batshuayi',     clubs: ['Standard Liège', 'Marseille', 'Chelsea', 'Borussia Dortmund', 'Crystal Palace'], nationality: 'Belgian' },
  { name: 'Nacer Chadli',        clubs: ['Twente', 'Tottenham', 'West Brom', 'Monaco', 'Anderlecht'],            nationality: 'Belgian' },
  { name: 'Toby Alderweireld',   clubs: ['Ajax', 'Atletico Madrid', 'Southampton', 'Tottenham', 'Al Duhail'],    nationality: 'Belgian' },
  { name: 'Jan Vertonghen',      clubs: ['Ajax', 'Tottenham', 'Benfica', 'Anderlecht'],                           nationality: 'Belgian' },
  { name: 'Radja Nainggolan',    clubs: ['Piacenza', 'Cagliari', 'Roma', 'Inter Milan', 'Cagliari'],             nationality: 'Belgian' },
  { name: 'Thomas Meunier',      clubs: ['Club Brugge', 'PSG', 'Borussia Dortmund', 'Trabzonspor'],             nationality: 'Belgian' },
  { name: 'Yannick Carrasco',    clubs: ['Monaco', 'Atletico Madrid', 'Dalian Professional', 'Atletico Madrid'], nationality: 'Belgian' },
  { name: 'Thorgan Hazard',      clubs: ['Chelsea', 'Zulte Waregem', 'Borussia Mönchengladbach', 'Borussia Dortmund', 'PSV'], nationality: 'Belgian' },
  { name: 'Romelu Lukaku',       clubs: ['Anderlecht', 'Chelsea', 'West Brom', 'Everton', 'Manchester United', 'Inter Milan'], nationality: 'Belgian' },
  { name: 'Erling Haaland',      clubs: ['Bryne', 'Molde', 'Red Bull Salzburg', 'Borussia Dortmund', 'Manchester City'], nationality: 'Norwegian' },
  { name: 'Martin Ødegaard',     clubs: ['Strømsgodset', 'Real Madrid', 'Heerenveen', 'Vitesse', 'Real Sociedad', 'Arsenal'], nationality: 'Norwegian' },
  { name: 'Alexander Sørloth',   clubs: ['Rosenborg', 'Crystal Palace', 'Trabzonspor', 'RB Leipzig', 'Villarreal', 'Atletico Madrid'], nationality: 'Norwegian' },
  { name: 'Jude Bellingham',     clubs: ['Birmingham', 'Borussia Dortmund', 'Real Madrid'],                       nationality: 'English' },
  { name: 'Bukayo Saka',         clubs: ['Arsenal'],                                                              nationality: 'English' },
  { name: 'Phil Foden',          clubs: ['Manchester City'],                                                      nationality: 'English' },
  { name: 'Declan Rice',         clubs: ['West Ham', 'Arsenal'],                                                  nationality: 'English' },
  { name: 'Jack Grealish',       clubs: ['Aston Villa', 'Manchester City'],                                       nationality: 'English' },
  { name: 'Mason Mount',         clubs: ['Chelsea', 'Derby', 'Manchester United', 'Liverpool'],                   nationality: 'English' },
  { name: 'Jadon Sancho',        clubs: ['Manchester City', 'Borussia Dortmund', 'Manchester United', 'Chelsea'], nationality: 'English' },
  { name: 'Trent Alexander-Arnold', clubs: ['Liverpool', 'Real Madrid'],                                          nationality: 'English' },
  { name: 'Kobbie Mainoo',       clubs: ['Manchester United'],                                                    nationality: 'English' },
  { name: 'Lamine Yamal',        clubs: ['Barcelona'],                                                            nationality: 'Spanish' },
  { name: 'Pedri',               clubs: ['Las Palmas', 'Barcelona'],                                              nationality: 'Spanish' },
  { name: 'Gavi',                clubs: ['Barcelona'],                                                            nationality: 'Spanish' },
  { name: 'Nico Williams',       clubs: ['Athletic Bilbao'],                                                      nationality: 'Spanish' },
  { name: 'Ferran Torres',       clubs: ['Valencia', 'Manchester City', 'Barcelona'],                             nationality: 'Spanish' },
  { name: 'Dani Olmo',           clubs: ['Barcelona', 'Dinamo Zagreb', 'RB Leipzig', 'Barcelona'],               nationality: 'Spanish' },
  { name: 'Ansu Fati',           clubs: ['Barcelona'],                                                            nationality: 'Spanish' },
  { name: 'Mikel Oyarzabal',     clubs: ['Real Sociedad'],                                                        nationality: 'Spanish' },
  { name: 'Marcos Llorente',     clubs: ['Real Madrid', 'Alaves', 'Real Madrid', 'Atletico Madrid'],             nationality: 'Spanish' },
  { name: 'Marco Asensio',       clubs: ['Mallorca', 'Espanyol', 'Real Madrid', 'PSG', 'Aston Villa'],           nationality: 'Spanish' },
  { name: 'Florian Wirtz',       clubs: ['Bayer Leverkusen'],                                                     nationality: 'German' },
  { name: 'Jamal Musiala',       clubs: ['Chelsea', 'Bayern Munich'],                                             nationality: 'German' },
  { name: 'Xavi Simons',         clubs: ['PSG', 'PSV', 'RB Leipzig', 'Paris Saint-Germain'],                     nationality: 'Dutch' },
  { name: 'Ryan Gravenberch',    clubs: ['Ajax', 'Bayern Munich', 'Liverpool'],                                   nationality: 'Dutch' },
  { name: 'Cody Gakpo',          clubs: ['PSV', 'Liverpool'],                                                     nationality: 'Dutch' },
  { name: 'Virgil van Dijk',     clubs: ['Groningen', 'Celtic', 'Southampton', 'Liverpool'],                      nationality: 'Dutch' },
  { name: 'Memphis Depay',       clubs: ['PSV', 'Manchester United', 'Lyon', 'Barcelona', 'Atletico Madrid', 'Corinthians'], nationality: 'Dutch' },
  { name: 'Daley Blind',         clubs: ['Ajax', 'Manchester United', 'Ajax', 'Bayern Munich', 'Girona'],        nationality: 'Dutch' },
  { name: 'Stefan de Vrij',      clubs: ['Feyenoord', 'Lazio', 'Inter Milan'],                                   nationality: 'Dutch' },
  { name: 'Matthijs de Ligt',    clubs: ['Ajax', 'Juventus', 'Bayern Munich', 'Manchester United'],              nationality: 'Dutch' },
  { name: 'Frenkie de Jong',     clubs: ['Ajax', 'Barcelona'],                                                    nationality: 'Dutch' },
  { name: 'Wout Weghorst',       clubs: ['AZ', 'Wolfsburg', 'Burnley', 'Besiktas', 'Manchester United', 'Hoffenheim'], nationality: 'Dutch' },
  { name: 'Vinicius Junior',     clubs: ['Flamengo', 'Real Madrid'],                                              nationality: 'Brazilian' },
  { name: 'Rodrygo',             clubs: ['Santos', 'Real Madrid'],                                                nationality: 'Brazilian' },
  { name: 'Endrick',             clubs: ['Palmeiras', 'Real Madrid'],                                             nationality: 'Brazilian' },
  { name: 'Richarlison',         clubs: ['América Mineiro', 'Fluminense', 'Watford', 'Everton', 'Tottenham'],    nationality: 'Brazilian' },
  { name: 'Antony',              clubs: ['São Paulo', 'Ajax', 'Manchester United'],                               nationality: 'Brazilian' },
  { name: 'Raphinha',            clubs: ['Vitória de Guimarães', 'Rennes', 'Leeds', 'Barcelona'],                nationality: 'Brazilian' },
  { name: 'Éder Militão',        clubs: ['São Paulo', 'Porto', 'Real Madrid'],                                    nationality: 'Brazilian' },
  { name: 'Gabriel Magalhães',   clubs: ['Dinamo Zagreb', 'Lille', 'Arsenal'],                                   nationality: 'Brazilian' },
  { name: 'Gleison Bremer',      clubs: ['Atlético Mineiro', 'Torino', 'Juventus'],                              nationality: 'Brazilian' },
  { name: 'Alisson Becker',      clubs: ['Internacional', 'Roma', 'Liverpool'],                                   nationality: 'Brazilian' },
  { name: 'Ederson',             clubs: ['Ribeirão', 'Benfica', 'Manchester City'],                               nationality: 'Brazilian' },
  { name: 'Romário Baro',        clubs: ['Porto', 'Estoril'],                                                     nationality: 'Portuguese' },
  { name: 'Alejandro Garnacho',  clubs: ['Atletico Madrid', 'Manchester United'],                                  nationality: 'Argentinian' },
  { name: 'Enzo Fernández',      clubs: ['River Plate', 'Benfica', 'Chelsea'],                                    nationality: 'Argentinian' },
  { name: 'Alexis Mac Allister', clubs: ['Argentinos Juniors', 'Brighton', 'Liverpool'],                          nationality: 'Argentinian' },
  { name: 'Rodrigo De Paul',     clubs: ['Racing Club', 'Valencia', 'Udinese', 'Atletico Madrid'],               nationality: 'Argentinian' },
  { name: 'Leandro Paredes',     clubs: ['Roma', 'Empoli', 'Chievo', 'Boca Juniors', 'Zenit', 'PSG', 'Juventus', 'Roma'], nationality: 'Argentinian' },
  { name: 'Nicolás González',    clubs: ['Argentinos Juniors', 'Stuttgart', 'Fiorentina', 'Juventus'],           nationality: 'Argentinian' },
  { name: 'Julián Álvarez',      clubs: ['River Plate', 'Manchester City', 'Atletico Madrid'],                    nationality: 'Argentinian' },
  { name: 'Lisandro Martínez',   clubs: ['Defensa y Justicia', 'Ajax', 'Manchester United'],                      nationality: 'Argentinian' },
  { name: 'Germán Pezzella',     clubs: ['River Plate', 'Fiorentina', 'Betis', 'Parma'],                         nationality: 'Argentinian' },
  { name: 'Nahuel Molina',       clubs: ['Boca Juniors', 'Udinese', 'Atletico Madrid'],                           nationality: 'Argentinian' },
  { name: 'Thiago Almada',       clubs: ['Vélez Sársfield', 'Atlanta United', 'Al Duhail', 'Lyon'],             nationality: 'Argentinian' },
  { name: 'Exequiel Palacios',   clubs: ['River Plate', 'Bayer Leverkusen'],                                      nationality: 'Argentinian' },
  { name: 'Nicolás Tagliafico',  clubs: ['Banfield', 'Racing Club', 'Ajax', 'Nice', 'Lyon'],                     nationality: 'Argentinian' },
  { name: 'Nicolás Otamendi',    clubs: ['Vélez', 'Porto', 'Valencia', 'Manchester City', 'Benfica'],            nationality: 'Argentinian' },
  { name: 'Lionel Scaloni',      clubs: ['Newell\'s', 'Deportivo', 'Lazio', 'West Ham', 'Mallorca', 'Racing Club'], nationality: 'Argentinian' },
  { name: 'Federico Chiesa',     clubs: ['Fiorentina', 'Juventus', 'Liverpool'],                                  nationality: 'Italian' },
  { name: 'Sandro Tonali',       clubs: ['Brescia', 'AC Milan', 'Newcastle'],                                     nationality: 'Italian' },
  { name: 'Nicolo Barella',      clubs: ['Cagliari', 'Inter Milan'],                                              nationality: 'Italian' },
  { name: 'Gianluigi Donnarumma',clubs: ['AC Milan', 'PSG'],                                                      nationality: 'Italian' },
  { name: 'Alessandro Bastoni',  clubs: ['Atalanta', 'Parma', 'Inter Milan'],                                     nationality: 'Italian' },
  { name: 'Giovanni Di Lorenzo', clubs: ['Empoli', 'Napoli'],                                                     nationality: 'Italian' },
  { name: 'Rafael Leão',         clubs: ['Sporting CP', 'Lille', 'AC Milan'],                                     nationality: 'Portuguese' },
  { name: 'Vitinha',             clubs: ['Porto', 'Wolverhampton', 'Porto', 'PSG'],                               nationality: 'Portuguese' },
  { name: 'Otávio',             clubs: ['Porto'],                                                                  nationality: 'Portuguese' },
  { name: 'Gonçalo Ramos',       clubs: ['Benfica', 'PSG'],                                                       nationality: 'Portuguese' },
  { name: 'Mattéo Guendouzi',    clubs: ['Lorient', 'Arsenal', 'Hertha Berlin', 'Marseille', 'Lazio'],           nationality: 'French' },
  { name: 'Eduardo Camavinga',   clubs: ['Rennes', 'Real Madrid'],                                                nationality: 'French' },
  { name: 'Aurélien Tchouaméni', clubs: ['Bordeaux', 'Monaco', 'Real Madrid'],                                    nationality: 'French' },
  { name: 'William Saliba',      clubs: ['Saint-Étienne', 'Arsenal', 'Nice', 'Marseille', 'Arsenal'],            nationality: 'French' },
  { name: 'Randal Kolo Muani',   clubs: ['FC Nantes', 'Eintracht Frankfurt', 'PSG', 'Juventus'],                 nationality: 'French' },
  { name: 'Marcus Thuram',       clubs: ['Guingamp', 'Nice', 'Borussia Mönchengladbach', 'Inter Milan'],         nationality: 'French' },
  { name: 'Bradley Barcola',     clubs: ['Lyon', 'PSG'],                                                          nationality: 'French' },
  { name: 'Kingsley Coman',      clubs: ['PSG', 'Juventus', 'Bayern Munich'],                                     nationality: 'French' },
  { name: 'Christopher Nkunku',  clubs: ['PSG', 'Leipzig', 'Chelsea'],                                            nationality: 'French' },
  { name: 'Jules Koundé',        clubs: ['Bordeaux', 'Sevilla', 'Barcelona'],                                     nationality: 'French' },
  { name: 'Presnel Kimpembe',    clubs: ['PSG'],                                                                   nationality: 'French' },
  { name: 'Theo Hernández',      clubs: ['Atletico Madrid', 'Alaves', 'Real Madrid', 'Real Sociedad', 'AC Milan'], nationality: 'French' },
  { name: 'Lucas Hernández',     clubs: ['Atletico Madrid', 'Bayern Munich', 'PSG'],                              nationality: 'French' },
  { name: 'Jonathan Clauss',     clubs: ['Lens', 'Marseille'],                                                    nationality: 'French' },
  { name: 'Mike Maignan',        clubs: ['PSG', 'Lille', 'AC Milan'],                                             nationality: 'French' },
  { name: 'Idrissa Gueye',       clubs: ['Lille', 'Aston Villa', 'Everton', 'PSG', 'Everton'],                   nationality: 'Senegalese' },
  { name: 'Sadio Mané',          clubs: ['Metz', 'Red Bull Salzburg', 'Southampton', 'Liverpool', 'Bayern Munich', 'Al Nassr'], nationality: 'Senegalese' },
  { name: 'Kalidou Koulibaly',   clubs: ['Metz', 'Genk', 'Napoli', 'Chelsea', 'Al Hilal'],                      nationality: 'Senegalese' },
  { name: 'Édouard Mendy',       clubs: ['Marseille', 'Reims', 'Rennes', 'Chelsea', 'Al Ahli'],                  nationality: 'Senegalese' },
  { name: 'Ismaila Sarr',        clubs: ['Metz', 'Rennes', 'Watford', 'Crystal Palace'],                         nationality: 'Senegalese' },
  { name: 'Pape Matar Sarr',     clubs: ['Génération Foot', 'Metz', 'Tottenham'],                                 nationality: 'Senegalese' },
  { name: 'Victor Osimhen',      clubs: ['Ultimate Strikers', 'Wolfsburg', 'Charleroi', 'Lille', 'Napoli', 'Galatasaray'], nationality: 'Nigerian' },
  { name: 'Samuel Chukwueze',    clubs: ['Villarreal', 'AC Milan'],                                               nationality: 'Nigerian' },
  { name: 'Wilfried Zaha',       clubs: ['Crystal Palace', 'Manchester United', 'Cardiff', 'Crystal Palace', 'Galatasaray'], nationality: 'Ivorian' },
  { name: 'Nicolas Pépé',        clubs: ['Angers', 'Lille', 'Arsenal', 'Nice'],                                   nationality: 'Ivorian' },
  { name: 'Sébastien Haller',    clubs: ['Tours', 'Utrecht', 'Eintracht Frankfurt', 'West Ham', 'Ajax', 'Borussia Dortmund'], nationality: 'Ivorian' },
  { name: 'Serge Aurier',        clubs: ['Toulouse', 'PSG', 'Tottenham', 'Villarreal'],                           nationality: 'Ivorian' },
  { name: 'Eric Bailly',         clubs: ['Espanyol', 'Villarreal', 'Manchester United', 'Marseille'],             nationality: 'Ivorian' },
  { name: 'Riyad Mahrez',        clubs: ['Le Havre', 'Quimper', 'Leicester', 'Manchester City', 'Al Ahli'],      nationality: 'Algerian' },
  { name: 'Islam Slimani',       clubs: ['USM Alger', 'Sporting CP', 'Leicester', 'Newcastle', 'Monaco', 'Lyon'], nationality: 'Algerian' },
  { name: 'Yacine Brahimi',      clubs: ['Rennes', 'Granada', 'Porto', 'Al Rayyan'],                              nationality: 'Algerian' },
  { name: 'Andy Robertson',      clubs: ['Queen\'s Park', 'Dundee United', 'Hull', 'Liverpool'],                  nationality: 'Scottish' },
  { name: 'Scott McTominay',     clubs: ['Manchester United', 'Napoli'],                                           nationality: 'Scottish' },
  { name: 'Kieran Tierney',      clubs: ['Celtic', 'Arsenal', 'Real Sociedad'],                                   nationality: 'Scottish' },
  { name: 'Robert Snodgrass',    clubs: ['Leeds', 'Watford', 'Norwich', 'Hull', 'Aston Villa', 'West Ham'],      nationality: 'Scottish' },
  { name: 'Gareth Bale',         clubs: ['Southampton', 'Tottenham', 'Real Madrid', 'LAFC'],                     nationality: 'Welsh' },
  { name: 'Aaron Ramsey',        clubs: ['Cardiff', 'Arsenal', 'Juventus', 'Rangers'],                           nationality: 'Welsh' },
  { name: 'Joe Allen',           clubs: ['Swansea', 'Liverpool', 'Stoke', 'Swansea'],                            nationality: 'Welsh' },
  { name: 'Ben Davies',          clubs: ['Swansea', 'Tottenham'],                                                  nationality: 'Welsh' },
  { name: 'Chris Gunter',        clubs: ['Cardiff', 'Tottenham', 'Nottingham Forest', 'Reading'],                 nationality: 'Welsh' },
  { name: 'Seamus Coleman',      clubs: ['Sligo Rovers', 'Everton'],                                              nationality: 'Irish' },
  { name: 'Séamus Coleman',      clubs: ['Sligo Rovers', 'Everton'],                                              nationality: 'Irish' },
  { name: 'Robbie Keane',        clubs: ['Wolverhampton', 'Coventry', 'Inter Milan', 'Leeds', 'Tottenham', 'Liverpool', 'Celtic', 'LA Galaxy'], nationality: 'Irish' },
  { name: 'Damien Duff',         clubs: ['Blackburn', 'Chelsea', 'Newcastle', 'Fulham'],                         nationality: 'Irish' },
  { name: 'Shay Given',          clubs: ['Blackburn', 'Swindon', 'Newcastle', 'Manchester City', 'Aston Villa'], nationality: 'Irish' },
  { name: 'Zlatan Ibrahimović',  clubs: ['Malmö', 'Ajax', 'Juventus', 'Inter Milan', 'Barcelona', 'AC Milan', 'PSG', 'Manchester United', 'AC Milan'], nationality: 'Swedish' },
  { name: 'Henrik Larsson',      clubs: ['Helsingborg', 'Feyenoord', 'Celtic', 'Barcelona', 'Manchester United', 'Helsingborg'], nationality: 'Swedish' },
  { name: 'Freddie Ljungberg',   clubs: ['Halmstad', 'Arsenal', 'West Ham', 'Barcelona', 'Seattle'],            nationality: 'Swedish' },
  { name: 'Olof Mellberg',       clubs: ['AIK', 'Racing Santander', 'Aston Villa', 'Juventus', 'Celtic'],        nationality: 'Swedish' },
  { name: 'Kim Källström',       clubs: ['Djurgården', 'Rennes', 'Lyon', 'Spartak Moscow', 'Galatasaray'],       nationality: 'Swedish' },
  { name: 'Dejan Kulusevski',    clubs: ['Atalanta', 'Parma', 'Juventus', 'Tottenham'],                          nationality: 'Swedish' },
  { name: 'Alexander Isak',      clubs: ['AIK', 'Borussia Dortmund', 'Willem II', 'Real Sociedad', 'Newcastle'], nationality: 'Swedish' },
  { name: 'Emil Forsberg',       clubs: ['GIF Sundsvall', 'Malmö', 'RB Leipzig', 'New York RB'],                 nationality: 'Swedish' },
  { name: 'Ola Toivonen',        clubs: ['Malmö', 'PSV', 'Rennes', 'Toulouse', 'Melbourne Victory'],            nationality: 'Swedish' },
  { name: 'Victor Nilsson Lindelöf', clubs: ['Västerås', 'Benfica', 'Manchester United'],                        nationality: 'Swedish' },
  { name: 'Peter Crouch',        clubs: ['Tottenham', 'Aston Villa', 'Southampton', 'Liverpool', 'Portsmouth', 'Stoke'], nationality: 'English' },
  { name: 'Robbie Fowler',       clubs: ['Liverpool', 'Leeds', 'Manchester City', 'Liverpool'],                  nationality: 'English' },
  { name: 'Les Ferdinand',       clubs: ['QPR', 'Newcastle', 'Tottenham', 'Leicester'],                          nationality: 'English' },
  { name: 'Ian Wright',          clubs: ['Crystal Palace', 'Arsenal', 'West Ham'],                               nationality: 'English' },
  { name: 'Teddy Sheringham',    clubs: ['Nottingham Forest', 'Tottenham', 'Manchester United', 'Portsmouth'],   nationality: 'English' },
  { name: 'Emmanuel Adebayor',   clubs: ['Arsenal', 'Manchester City', 'Real Madrid', 'Tottenham', 'Crystal Palace'], nationality: 'Togolese' },
  { name: 'Michael Essien',      clubs: ['Bastia', 'Lyon', 'Chelsea', 'AC Milan', 'Real Madrid'],               nationality: 'Ghanaian' },
  { name: 'Asamoah Gyan',        clubs: ['Liberty Professionals', 'Udinese', 'Rennes', 'Sunderland', 'Al Ain'], nationality: 'Ghanaian' },
  { name: 'André Ayew',          clubs: ['Marseille', 'Lorient', 'Swansea', 'Guangzhou', 'West Ham'],           nationality: 'Ghanaian' },
  { name: 'Thomas Partey',       clubs: ['Atletico Madrid', 'Arsenal'],                                          nationality: 'Ghanaian' },
  { name: 'Sulley Muntari',       clubs: ['Liberty', 'Udinese', 'Portsmouth', 'Inter Milan', 'AC Milan'],        nationality: 'Ghanaian' },
  { name: 'Yaya Touré',          clubs: ['ASEC Mimosas', 'Metalurh Donetsk', 'Olimpik Donetsk', 'Beveren', 'Dynamo Kyiv', 'Monaco', 'Barcelona', 'Manchester City'], nationality: 'Ivorian' },
  { name: 'Drogba',              clubs: ['Le Mans', 'Gueugnon', 'Marseille', 'Chelsea', 'Galatasaray'],          nationality: 'Ivorian' },
  { name: 'Wilfried Bony',       clubs: ['Vitesse', 'Swansea', 'Manchester City', 'Stoke'],                     nationality: 'Ivorian' },
  { name: 'Salomon Kalou',       clubs: ['Feyenoord', 'Chelsea', 'Lille', 'Hertha Berlin'],                     nationality: 'Ivorian' },
  { name: 'Emmanuel Eboué',      clubs: ['ASEC Mimosas', 'Arsenal', 'Galatasaray'],                              nationality: 'Ivorian' },
  { name: 'Cheikh Tioté',        clubs: ['FC Roskilde', 'Twente', 'Newcastle'],                                  nationality: 'Ivorian' },
  { name: 'Wahbi Khazri',        clubs: ['Ajaccio', 'Girondins de Bordeaux', 'Sunderland', 'Rennes', 'Saint-Étienne', 'Montpellier'], nationality: 'Tunisian' },
  { name: 'Yassine Bounou',      clubs: ['Wydad', 'Atlético Madrid', 'Girona', 'Sevilla', 'Al Hilal'],          nationality: 'Moroccan' },
  { name: 'Achraf Hakimi',       clubs: ['Real Madrid', 'Borussia Dortmund', 'Inter Milan', 'PSG'],             nationality: 'Moroccan' },
  { name: 'Hakim Ziyech',        clubs: ['Heerenveen', 'Twente', 'Ajax', 'Chelsea', 'Galatasaray', 'PSG'],      nationality: 'Moroccan' },
  { name: 'Sofiane Boufal',      clubs: ['Angers', 'Lille', 'Southampton', 'Celta Vigo', 'Angers'],             nationality: 'Moroccan' },
  { name: 'Youssef En-Nesyri',   clubs: ['Málaga', 'Leganés', 'Sevilla', 'Fenerbahçe'],                         nationality: 'Moroccan' },
  { name: 'Nayef Aguerd',        clubs: ['Dijon', 'Rennes', 'West Ham'],                                         nationality: 'Moroccan' },
  { name: 'Sofyan Amrabat',      clubs: ['Utrecht', 'Club Brugge', 'Verona', 'Fiorentina', 'Manchester United'], nationality: 'Moroccan' },
];

export function pickCareerPlayerForDate(dateStr: string): CareerPathPlayer {
  const seed = parseInt(dateStr.replace(/-/g, ''), 10);
  return CAREER_PATH_PLAYERS[seed % CAREER_PATH_PLAYERS.length];
}