export interface TransferRecord {
  player: string;
  from: string;
  to: string;
  year: number;
  fee: number; // milion €
}

export const TRANSFER_RECORDS: TransferRecord[] = [
  // ── REKORDET BOTËRORE ──
  { player: 'Neymar',              from: 'Barcelona',         to: 'PSG',                year: 2017, fee: 222 },
  { player: 'Kylian Mbappé',       from: 'Monaco',            to: 'PSG',                year: 2018, fee: 180 },
  { player: 'João Félix',          from: 'Benfica',           to: 'Atletico Madrid',    year: 2019, fee: 126 },
  { player: 'Philippe Coutinho',   from: 'Liverpool',         to: 'Barcelona',          year: 2018, fee: 142 },
  { player: 'Jack Grealish',       from: 'Aston Villa',       to: 'Manchester City',    year: 2021, fee: 117 },
  { player: 'Harry Maguire',       from: 'Leicester',         to: 'Manchester United',  year: 2019, fee: 87  },
  { player: 'Romelu Lukaku',       from: 'Inter Milan',       to: 'Chelsea',            year: 2021, fee: 113 },
  { player: 'Enzo Fernández',      from: 'Benfica',           to: 'Chelsea',            year: 2023, fee: 121 },
  { player: 'Moisés Caicedo',      from: 'Brighton',          to: 'Chelsea',            year: 2023, fee: 116 },
  { player: 'Declan Rice',         from: 'West Ham',          to: 'Arsenal',            year: 2023, fee: 105 },
  { player: 'Erling Haaland',      from: 'Dortmund',          to: 'Manchester City',    year: 2022, fee: 60  },
  { player: 'Antony',              from: 'Ajax',              to: 'Manchester United',  year: 2022, fee: 95  },
  { player: 'Darwin Núñez',        from: 'Benfica',           to: 'Liverpool',          year: 2022, fee: 75  },
  { player: 'Aurélien Tchouaméni', from: 'Monaco',            to: 'Real Madrid',        year: 2022, fee: 80  },
  { player: 'Jude Bellingham',     from: 'Dortmund',          to: 'Real Madrid',        year: 2023, fee: 103 },
  { player: 'Kylian Mbappé',       from: 'PSG',               to: 'Real Madrid',        year: 2024, fee: 0   },
  { player: 'Lamine Yamal',        from: 'Barcelona B',        to: 'Barcelona',          year: 2024, fee: 0   },
  // ── TRANSFERIMET HISTORIKE ──
  { player: 'Zinedine Zidane',     from: 'Juventus',          to: 'Real Madrid',        year: 2001, fee: 77  },
  { player: 'Luís Figo',           from: 'Barcelona',         to: 'Real Madrid',        year: 2000, fee: 60  },
  { player: 'Ronaldo Nazário',     from: 'Inter Milan',       to: 'Real Madrid',        year: 2002, fee: 45  },
  { player: 'Ronaldo Nazário',     from: 'PSV',               to: 'Barcelona',          year: 1996, fee: 19  },
  { player: 'David Beckham',       from: 'Manchester United', to: 'Real Madrid',        year: 2003, fee: 35  },
  { player: 'Thierry Henry',       from: 'Juventus',          to: 'Arsenal',            year: 1999, fee: 11  },
  { player: 'Thierry Henry',       from: 'Arsenal',           to: 'Barcelona',          year: 2007, fee: 24  },
  { player: 'Ronaldinho',          from: 'PSG',               to: 'Barcelona',          year: 2003, fee: 30  },
  { player: 'Kaká',                from: 'AC Milan',          to: 'Real Madrid',        year: 2009, fee: 65  },
  { player: 'Cristiano Ronaldo',   from: 'Manchester United', to: 'Real Madrid',        year: 2009, fee: 94  },
  { player: 'Lionel Messi',        from: 'Barcelona',         to: 'PSG',                year: 2021, fee: 0   },
  { player: 'Gareth Bale',         from: 'Tottenham',         to: 'Real Madrid',        year: 2013, fee: 101 },
  { player: 'Zlatan Ibrahimović',  from: 'Ajax',              to: 'Juventus',           year: 2004, fee: 16  },
  { player: 'Zlatan Ibrahimović',  from: 'Juventus',          to: 'Inter Milan',        year: 2006, fee: 24  },
  { player: 'Zlatan Ibrahimović',  from: 'Inter Milan',       to: 'Barcelona',          year: 2009, fee: 69  },
  { player: 'Zlatan Ibrahimović',  from: 'AC Milan',          to: 'PSG',                year: 2012, fee: 21  },
  { player: 'Fernando Torres',     from: 'Liverpool',         to: 'Chelsea',            year: 2011, fee: 58  },
  { player: 'Fernando Torres',     from: 'Atletico Madrid',   to: 'Liverpool',          year: 2007, fee: 27  },
  { player: 'Wayne Rooney',        from: 'Everton',           to: 'Manchester United',  year: 2004, fee: 31  },
  { player: 'Samuel Eto\'o',       from: 'Mallorca',          to: 'Barcelona',          year: 2004, fee: 24  },
  { player: 'Didier Drogba',       from: 'Marseille',         to: 'Chelsea',            year: 2004, fee: 24  },
  { player: 'Andrés Iniesta',      from: 'Barcelona',         to: 'Vissel Kobe',        year: 2018, fee: 0   },
  { player: 'Xavi',                from: 'Barcelona',         to: 'Al Sadd',            year: 2015, fee: 0   },
  // ── TRANSFERIMET E MËDHA 2010-2020 ──
  { player: 'Eden Hazard',         from: 'Chelsea',           to: 'Real Madrid',        year: 2019, fee: 103 },
  { player: 'Virgil van Dijk',     from: 'Southampton',       to: 'Liverpool',          year: 2018, fee: 85  },
  { player: 'Alexis Sánchez',      from: 'Arsenal',           to: 'Manchester United',  year: 2018, fee: 0   },
  { player: 'Paul Pogba',          from: 'Juventus',          to: 'Manchester United',  year: 2016, fee: 105 },
  { player: 'Paul Pogba',          from: 'Manchester United', to: 'Juventus',           year: 2022, fee: 0   },
  { player: 'Ángel Di María',      from: 'Real Madrid',       to: 'Manchester United',  year: 2014, fee: 59  },
  { player: 'Ángel Di María',      from: 'Manchester United', to: 'PSG',                year: 2015, fee: 49  },
  { player: 'Mesut Özil',          from: 'Real Madrid',       to: 'Arsenal',            year: 2013, fee: 50  },
  { player: 'Radamel Falcao',      from: 'Porto',             to: 'Atletico Madrid',    year: 2011, fee: 40  },
  { player: 'Radamel Falcao',      from: 'Atletico Madrid',   to: 'Monaco',             year: 2013, fee: 60  },
  { player: 'James Rodríguez',     from: 'Monaco',            to: 'Real Madrid',        year: 2014, fee: 80  },
  { player: 'Gonzalo Higuaín',     from: 'Real Madrid',       to: 'Napoli',             year: 2013, fee: 40  },
  { player: 'Gonzalo Higuaín',     from: 'Napoli',            to: 'Juventus',           year: 2016, fee: 90  },
  { player: 'Álvaro Morata',       from: 'Juventus',          to: 'Chelsea',            year: 2017, fee: 66  },
  { player: 'Ousmane Dembélé',     from: 'Dortmund',          to: 'Barcelona',          year: 2017, fee: 105 },
  { player: 'Coutinho',            from: 'Liverpool',         to: 'Barcelona',          year: 2018, fee: 142 },
  { player: 'Antoine Griezmann',   from: 'Atletico Madrid',   to: 'Barcelona',          year: 2019, fee: 120 },
  { player: 'Antoine Griezmann',   from: 'Barcelona',         to: 'Atletico Madrid',    year: 2021, fee: 40  },
  { player: 'Karim Benzema',       from: 'Real Madrid',       to: 'Al Ittihad',         year: 2023, fee: 0   },
  { player: 'N\'Golo Kanté',       from: 'Leicester',         to: 'Chelsea',            year: 2016, fee: 32  },
  { player: 'N\'Golo Kanté',       from: 'Chelsea',           to: 'Al Ittihad',         year: 2023, fee: 0   },
  { player: 'Romelu Lukaku',       from: 'Everton',           to: 'Manchester United',  year: 2017, fee: 84  },
  { player: 'Romelu Lukaku',       from: 'Manchester United', to: 'Inter Milan',        year: 2019, fee: 74  },
  { player: 'Naby Keïta',          from: 'RB Leipzig',        to: 'Liverpool',          year: 2018, fee: 52  },
  { player: 'Fabinho',             from: 'Monaco',            to: 'Liverpool',          year: 2018, fee: 43  },
  { player: 'Alisson',             from: 'Roma',              to: 'Liverpool',          year: 2018, fee: 62  },
  { player: 'Kepa Arrizabalaga',   from: 'Athletic Bilbao',   to: 'Chelsea',            year: 2018, fee: 80  },
  { player: 'Ben Chilwell',        from: 'Leicester',         to: 'Chelsea',            year: 2020, fee: 50  },
  { player: 'Hakim Ziyech',        from: 'Ajax',              to: 'Chelsea',            year: 2020, fee: 40  },
  { player: 'Timo Werner',         from: 'RB Leipzig',        to: 'Chelsea',            year: 2020, fee: 53  },
  { player: 'Kai Havertz',         from: 'Bayer Leverkusen',  to: 'Chelsea',            year: 2020, fee: 80  },
  { player: 'Kai Havertz',         from: 'Chelsea',           to: 'Arsenal',            year: 2023, fee: 75  },
  { player: 'Lionel Messi',        from: 'PSG',               to: 'Inter Miami',        year: 2023, fee: 0   },
  { player: 'Luis Suárez',         from: 'Barcelona',         to: 'Atletico Madrid',    year: 2020, fee: 0   },
  { player: 'Luis Suárez',         from: 'Liverpool',         to: 'Barcelona',          year: 2014, fee: 82  },
  { player: 'Cesc Fàbregas',       from: 'Arsenal',           to: 'Barcelona',          year: 2011, fee: 35  },
  { player: 'Cesc Fàbregas',       from: 'Barcelona',         to: 'Chelsea',            year: 2014, fee: 33  },
  // ── TRANSFERIMET SURPRIZË ──
  { player: 'Nicolas Anelka',      from: 'Arsenal',           to: 'Real Madrid',        year: 1999, fee: 23  },
  { player: 'Michael Owen',        from: 'Liverpool',         to: 'Real Madrid',        year: 2004, fee: 12  },
  { player: 'Michael Owen',        from: 'Newcastle',         to: 'Manchester United',  year: 2009, fee: 1   },
  { player: 'Sol Campbell',        from: 'Tottenham',         to: 'Arsenal',            year: 2001, fee: 0   },
  { player: 'Carlos Tevez',        from: 'Manchester United', to: 'Manchester City',    year: 2009, fee: 47  },
  { player: 'Emmanuel Adebayor',   from: 'Arsenal',           to: 'Manchester City',    year: 2009, fee: 25  },
  { player: 'Samir Nasri',         from: 'Arsenal',           to: 'Manchester City',    year: 2011, fee: 25  },
  { player: 'Robin van Persie',    from: 'Arsenal',           to: 'Manchester United',  year: 2012, fee: 26  },
  { player: 'Luis Suárez',         from: 'Ajax',              to: 'Liverpool',          year: 2011, fee: 23  },
  { player: 'Sadio Mané',          from: 'Red Bull Salzburg', to: 'Southampton',        year: 2014, fee: 4   },
  { player: 'Sadio Mané',          from: 'Southampton',       to: 'Liverpool',          year: 2016, fee: 34  },
  { player: 'Sadio Mané',          from: 'Liverpool',         to: 'Bayern Munich',      year: 2022, fee: 32  },
  { player: 'Mohamed Salah',       from: 'Chelsea',           to: 'Roma',               year: 2015, fee: 16  },
  { player: 'Mohamed Salah',       from: 'Roma',              to: 'Liverpool',          year: 2017, fee: 42  },
  { player: 'Riyad Mahrez',        from: 'Leicester',         to: 'Manchester City',    year: 2018, fee: 60  },
  { player: 'Robert Lewandowski',  from: 'Dortmund',          to: 'Bayern Munich',      year: 2014, fee: 0   },
  { player: 'Robert Lewandowski',  from: 'Bayern Munich',     to: 'Barcelona',          year: 2022, fee: 45  },
  { player: 'Harry Kane',          from: 'Tottenham',         to: 'Bayern Munich',      year: 2023, fee: 100 },
  { player: 'Raheem Sterling',     from: 'Liverpool',         to: 'Manchester City',    year: 2015, fee: 49  },
  { player: 'Raheem Sterling',     from: 'Manchester City',   to: 'Chelsea',            year: 2022, fee: 47  },
  { player: 'Kevin De Bruyne',     from: 'Wolfsburg',         to: 'Manchester City',    year: 2015, fee: 76  },
  { player: 'Leroy Sané',          from: 'Manchester City',   to: 'Bayern Munich',      year: 2020, fee: 49  },
  { player: 'Jadon Sancho',        from: 'Dortmund',          to: 'Manchester United',  year: 2021, fee: 85  },
  { player: 'Raphael Varane',      from: 'Real Madrid',       to: 'Manchester United',  year: 2021, fee: 42  },
  { player: 'Jadon Sancho',        from: 'Manchester United', to: 'Chelsea',            year: 2024, fee: 0   },
  { player: 'Mason Mount',         from: 'Chelsea',           to: 'Manchester United',  year: 2023, fee: 60  },
  { player: 'Casemiro',            from: 'Real Madrid',       to: 'Manchester United',  year: 2022, fee: 70  },
  { player: 'Lisandro Martínez',   from: 'Ajax',              to: 'Manchester United',  year: 2022, fee: 57  },
  { player: 'Antony',              from: 'Ajax',              to: 'Manchester United',  year: 2022, fee: 95  },
  // ── TRANSFERIMET ITALIANE ──
  { player: 'Ronaldo Nazário',     from: 'Barcelona',         to: 'Inter Milan',        year: 1997, fee: 27  },
  { player: 'Hernán Crespo',       from: 'Parma',             to: 'Lazio',              year: 2000, fee: 56  },
  { player: 'Zlatan Ibrahimović',  from: 'Manchester United', to: 'AC Milan',           year: 2020, fee: 0   },
  { player: 'Cristiano Ronaldo',   from: 'Real Madrid',       to: 'Juventus',           year: 2018, fee: 117 },
  { player: 'Cristiano Ronaldo',   from: 'Juventus',          to: 'Manchester United',  year: 2021, fee: 20  },
  { player: 'Dybala',              from: 'Palermo',           to: 'Juventus',           year: 2015, fee: 32  },
  { player: 'Paulo Dybala',        from: 'Juventus',          to: 'Roma',               year: 2022, fee: 0   },
  { player: 'Matthijs de Ligt',    from: 'Ajax',              to: 'Juventus',           year: 2019, fee: 75  },
  { player: 'Matthijs de Ligt',    from: 'Juventus',          to: 'Bayern Munich',      year: 2022, fee: 67  },
  { player: 'Romelu Lukaku',       from: 'Chelsea',           to: 'Inter Milan',        year: 2022, fee: 8   },
  { player: 'Lautaro Martínez',    from: 'Racing Club',       to: 'Inter Milan',        year: 2018, fee: 22  },
  { player: 'Achraf Hakimi',       from: 'Real Madrid',       to: 'Inter Milan',        year: 2020, fee: 40  },
  { player: 'Achraf Hakimi',       from: 'Inter Milan',       to: 'PSG',                year: 2021, fee: 68  },
  { player: 'Victor Osimhen',      from: 'Lille',             to: 'Napoli',             year: 2020, fee: 70  },
  { player: 'Hirving Lozano',      from: 'PSV',               to: 'Napoli',             year: 2019, fee: 42  },
  { player: 'Kalidou Koulibaly',   from: 'Napoli',            to: 'Chelsea',            year: 2022, fee: 38  },
  { player: 'Lorenzo Insigne',     from: 'Napoli',            to: 'Toronto FC',         year: 2022, fee: 0   },
  { player: 'Khvicha Kvaratskhelia',from: 'Dinamo Batumi',    to: 'Napoli',             year: 2022, fee: 10  },
  // ── TRANSFERIMET SPANJOLLE ──
  { player: 'Gareth Bale',         from: 'Real Madrid',       to: 'LAFC',               year: 2022, fee: 0   },
  { player: 'James Rodríguez',     from: 'Real Madrid',       to: 'Bayern Munich',      year: 2017, fee: 42  },
  { player: 'James Rodríguez',     from: 'Bayern Munich',     to: 'Everton',            year: 2020, fee: 25  },
  { player: 'Toni Kroos',          from: 'Bayern Munich',     to: 'Real Madrid',        year: 2014, fee: 25  },
  { player: 'Luka Modrić',         from: 'Tottenham',         to: 'Real Madrid',        year: 2012, fee: 30  },
  { player: 'Isco',                from: 'Málaga',            to: 'Real Madrid',        year: 2013, fee: 30  },
  { player: 'Asensio',             from: 'Mallorca',          to: 'Real Madrid',        year: 2014, fee: 4   },
  { player: 'Rodrygo',             from: 'Santos',            to: 'Real Madrid',        year: 2019, fee: 45  },
  { player: 'Vinicius Junior',     from: 'Flamengo',          to: 'Real Madrid',        year: 2018, fee: 45  },
  { player: 'Eduardo Camavinga',   from: 'Rennes',            to: 'Real Madrid',        year: 2021, fee: 31  },
  { player: 'Ferland Mendy',       from: 'Lyon',              to: 'Real Madrid',        year: 2019, fee: 48  },
  { player: 'Éder Militão',        from: 'Porto',             to: 'Real Madrid',        year: 2019, fee: 50  },
  { player: 'David Villa',         from: 'Valencia',          to: 'Barcelona',          year: 2010, fee: 40  },
  { player: 'Alexis Sánchez',      from: 'Udinese',           to: 'Barcelona',          year: 2011, fee: 26  },
  { player: 'Alexis Sánchez',      from: 'Barcelona',         to: 'Arsenal',            year: 2014, fee: 35  },
  { player: 'Ivan Rakitić',        from: 'Sevilla',           to: 'Barcelona',          year: 2014, fee: 18  },
  { player: 'Marc-André ter Stegen',from: 'Mönchengladbach',  to: 'Barcelona',          year: 2014, fee: 12  },
  { player: 'Frenkie de Jong',     from: 'Ajax',              to: 'Barcelona',          year: 2019, fee: 86  },
  { player: 'Pedri',               from: 'Las Palmas',        to: 'Barcelona',          year: 2020, fee: 5   },
  { player: 'Memphis Depay',       from: 'Lyon',              to: 'Barcelona',          year: 2021, fee: 0   },
  { player: 'Ferran Torres',       from: 'Manchester City',   to: 'Barcelona',          year: 2022, fee: 55  },
  { player: 'Lewandowski',         from: 'Bayern Munich',     to: 'Barcelona',          year: 2022, fee: 45  },
  { player: 'Raphinha',            from: 'Leeds',             to: 'Barcelona',          year: 2022, fee: 58  },
  { player: 'Diego Costa',         from: 'Chelsea',           to: 'Atletico Madrid',    year: 2017, fee: 57  },
  { player: 'Antoine Griezmann',   from: 'Real Sociedad',     to: 'Atletico Madrid',    year: 2014, fee: 30  },
  // ── TRANSFERIMET GJERMANE ──
  { player: 'Robert Lewandowski',  from: 'Lech Poznań',       to: 'Dortmund',           year: 2010, fee: 5   },
  { player: 'Mats Hummels',        from: 'Dortmund',          to: 'Bayern Munich',      year: 2016, fee: 35  },
  { player: 'Mario Götze',         from: 'Dortmund',          to: 'Bayern Munich',      year: 2013, fee: 37  },
  { player: 'Mario Götze',         from: 'Bayern Munich',     to: 'Dortmund',           year: 2016, fee: 22  },
  { player: 'Ivan Perišić',        from: 'Inter Milan',       to: 'Bayern Munich',      year: 2022, fee: 0   },
  { player: 'Manuel Neuer',        from: 'Schalke',           to: 'Bayern Munich',      year: 2011, fee: 30  },
  { player: 'Franck Ribéry',       from: 'Marseille',         to: 'Bayern Munich',      year: 2007, fee: 25  },
  { player: 'Arjen Robben',        from: 'Real Madrid',       to: 'Bayern Munich',      year: 2009, fee: 25  },
  { player: 'Xabi Alonso',         from: 'Real Madrid',       to: 'Bayern Munich',      year: 2014, fee: 9   },
  { player: 'Arturo Vidal',        from: 'Juventus',          to: 'Bayern Munich',      year: 2015, fee: 37  },
  { player: 'Douglas Costa',       from: 'Shakhtar',          to: 'Bayern Munich',      year: 2015, fee: 30  },
  { player: 'Renato Sanches',      from: 'Benfica',           to: 'Bayern Munich',      year: 2016, fee: 35  },
  { player: 'Corentin Tolisso',    from: 'Lyon',              to: 'Bayern Munich',      year: 2017, fee: 41  },
  { player: 'Lucas Hernández',     from: 'Atletico Madrid',   to: 'Bayern Munich',      year: 2019, fee: 80  },
  { player: 'Benjamin Pavard',     from: 'Stuttgart',         to: 'Bayern Munich',      year: 2019, fee: 35  },
  { player: 'Leon Goretzka',       from: 'Schalke',           to: 'Bayern Munich',      year: 2018, fee: 0   },
  { player: 'Serge Gnabry',        from: 'Werder Bremen',     to: 'Bayern Munich',      year: 2017, fee: 8   },
  { player: 'Sadio Mané',          from: 'Liverpool',         to: 'Bayern Munich',      year: 2022, fee: 32  },
  { player: 'Matthijs de Ligt',    from: 'Juventus',          to: 'Bayern Munich',      year: 2022, fee: 67  },
  // ── TRANSFERIMET FRANCEZE ──
  { player: 'Edinson Cavani',      from: 'Napoli',            to: 'PSG',                year: 2013, fee: 64  },
  { player: 'Thiago Silva',        from: 'AC Milan',          to: 'PSG',                year: 2012, fee: 42  },
  { player: 'David Beckham',       from: 'LA Galaxy',         to: 'PSG',                year: 2013, fee: 0   },
  { player: 'Zlatan Ibrahimović',  from: 'Barcelona',         to: 'AC Milan',           year: 2010, fee: 24  },
  { player: 'Lucas Moura',         from: 'São Paulo',         to: 'PSG',                year: 2013, fee: 45  },
  { player: 'Marquinhos',          from: 'Roma',              to: 'PSG',                year: 2013, fee: 31  },
  { player: 'Julian Draxler',      from: 'Wolfsburg',         to: 'PSG',                year: 2017, fee: 36  },
  { player: 'Marco Verratti',      from: 'Pescara',           to: 'PSG',                year: 2012, fee: 12  },
  { player: 'Layvin Kurzawa',      from: 'Monaco',            to: 'PSG',                year: 2015, fee: 25  },
  { player: 'Dani Alves',          from: 'Juventus',          to: 'PSG',                year: 2017, fee: 0   },
  { player: 'Kylian Mbappé',       from: 'PSG',               to: 'Real Madrid',        year: 2024, fee: 0   },
  { player: 'Lionel Messi',        from: 'PSG',               to: 'Inter Miami',        year: 2023, fee: 0   },
  { player: 'Sergio Ramos',        from: 'Real Madrid',       to: 'PSG',                year: 2021, fee: 0   },
  { player: 'Georginio Wijnaldum', from: 'Liverpool',         to: 'PSG',                year: 2021, fee: 0   },
  { player: 'Gigio Donnarumma',    from: 'AC Milan',          to: 'PSG',                year: 2021, fee: 0   },
  // ── TRANSFERIMET ANGLEZE ──
  { player: 'Andy Carroll',        from: 'Newcastle',         to: 'Liverpool',          year: 2011, fee: 35  },
  { player: 'Jordan Henderson',    from: 'Sunderland',        to: 'Liverpool',          year: 2011, fee: 16  },
  { player: 'Stewart Downing',     from: 'Aston Villa',       to: 'Liverpool',          year: 2011, fee: 20  },
  { player: 'Charlie Adam',        from: 'Blackpool',         to: 'Liverpool',          year: 2011, fee: 8   },
  { player: 'Xabi Alonso',         from: 'Liverpool',         to: 'Real Madrid',        year: 2009, fee: 30  },
  { player: 'Javier Mascherano',   from: 'Liverpool',         to: 'Barcelona',          year: 2010, fee: 24  },
  { player: 'Fernando Torres',     from: 'Chelsea',           to: 'AC Milan',           year: 2014, fee: 8   },
  { player: 'Thierry Henry',       from: 'Barcelona',         to: 'New York RB',        year: 2010, fee: 0   },
  { player: 'Peter Crouch',        from: 'Liverpool',         to: 'Portsmouth',         year: 2008, fee: 11  },
  { player: 'Dimitar Berbatov',    from: 'Tottenham',         to: 'Manchester United',  year: 2008, fee: 31  },
  { player: 'Michael Carrick',     from: 'Tottenham',         to: 'Manchester United',  year: 2006, fee: 18  },
  { player: 'Cristiano Ronaldo',   from: 'Sporting CP',       to: 'Manchester United',  year: 2003, fee: 17  },
  { player: 'Patrice Evra',        from: 'Monaco',            to: 'Manchester United',  year: 2006, fee: 6   },
  { player: 'Nemanja Vidić',       from: 'Spartak Moscow',    to: 'Manchester United',  year: 2006, fee: 7   },
  { player: 'Edwin van der Sar',   from: 'Fulham',            to: 'Manchester United',  year: 2005, fee: 2   },
  { player: 'Rio Ferdinand',       from: 'Leeds',             to: 'Manchester United',  year: 2002, fee: 30  },
  { player: 'Juan Sebastián Verón',from: 'Lazio',             to: 'Manchester United',  year: 2001, fee: 28  },
  { player: 'Ruud van Nistelrooy', from: 'PSV',               to: 'Manchester United',  year: 2001, fee: 19  },
  { player: 'Roy Keane',           from: 'Nottingham Forest', to: 'Manchester United',  year: 1993, fee: 4   },
  { player: 'Eric Cantona',        from: 'Leeds',             to: 'Manchester United',  year: 1992, fee: 1   },
  { player: 'Nicolas Anelka',      from: 'Arsenal',           to: 'Real Madrid',        year: 1999, fee: 23  },
  { player: 'Emmanuel Petit',      from: 'Arsenal',           to: 'Barcelona',          year: 2000, fee: 8   },
  { player: 'Marc Overmars',       from: 'Arsenal',           to: 'Barcelona',          year: 2000, fee: 40  },
  { player: 'Patrick Vieira',      from: 'Arsenal',           to: 'Juventus',           year: 2005, fee: 14  },
  { player: 'Ashley Cole',         from: 'Arsenal',           to: 'Chelsea',            year: 2006, fee: 5   },
  { player: 'William Gallas',      from: 'Chelsea',           to: 'Arsenal',            year: 2006, fee: 5   },
  { player: 'Petr Čech',           from: 'Chelsea',           to: 'Arsenal',            year: 2015, fee: 11  },
  { player: 'José Antonio Reyes',  from: 'Sevilla',           to: 'Arsenal',            year: 2004, fee: 17  },
  { player: 'Granit Xhaka',        from: 'Mönchengladbach',   to: 'Arsenal',            year: 2016, fee: 45  },
  { player: 'Alexandre Lacazette', from: 'Lyon',              to: 'Arsenal',            year: 2017, fee: 52  },
  { player: 'Pierre-Emerick Aubameyang', from: 'Dortmund',    to: 'Arsenal',            year: 2018, fee: 63  },
  { player: 'Nicolas Pépé',        from: 'Lille',             to: 'Arsenal',            year: 2019, fee: 80  },
  { player: 'Thomas Partey',       from: 'Atletico Madrid',   to: 'Arsenal',            year: 2020, fee: 45  },
  { player: 'Ben White',           from: 'Brighton',          to: 'Arsenal',            year: 2021, fee: 50  },
  { player: 'Martin Ødegaard',     from: 'Real Madrid',       to: 'Arsenal',            year: 2021, fee: 35  },
  { player: 'Gabriel Magalhães',   from: 'Lille',             to: 'Arsenal',            year: 2020, fee: 27  },
  // ── TRANSFERIMET PORTUGEZE DHE HOLLANDEZE ──
  { player: 'Frenkie de Jong',     from: 'Ajax',              to: 'Barcelona',          year: 2019, fee: 86  },
  { player: 'Matthijs de Ligt',    from: 'Ajax',              to: 'Juventus',           year: 2019, fee: 75  },
  { player: 'Hakim Ziyech',        from: 'Ajax',              to: 'Chelsea',            year: 2020, fee: 40  },
  { player: 'Donny van de Beek',   from: 'Ajax',              to: 'Manchester United',  year: 2020, fee: 40  },
  { player: 'Dusan Tadic',         from: 'Southampton',       to: 'Ajax',               year: 2018, fee: 12  },
  { player: 'Andre Onana',         from: 'Ajax',              to: 'Inter Milan',        year: 2023, fee: 0   },
  { player: 'Andre Onana',         from: 'Inter Milan',       to: 'Manchester United',  year: 2023, fee: 47  },
  { player: 'Ryan Gravenberch',    from: 'Ajax',              to: 'Bayern Munich',      year: 2022, fee: 19  },
  { player: 'Ryan Gravenberch',    from: 'Bayern Munich',     to: 'Liverpool',          year: 2023, fee: 40  },
  { player: 'Cody Gakpo',          from: 'PSV',               to: 'Liverpool',          year: 2023, fee: 45  },
  { player: 'Xavi Simons',         from: 'PSG',               to: 'PSV',                year: 2022, fee: 0   },
  { player: 'Bruno Fernandes',     from: 'Sporting CP',       to: 'Manchester United',  year: 2020, fee: 55  },
  { player: 'Rúben Dias',          from: 'Benfica',           to: 'Manchester City',    year: 2020, fee: 68  },
  { player: 'João Cancelo',        from: 'Juventus',          to: 'Manchester City',    year: 2019, fee: 65  },
  { player: 'João Cancelo',        from: 'Manchester City',   to: 'Bayern Munich',      year: 2023, fee: 0   },
  { player: 'João Félix',          from: 'Atletico Madrid',   to: 'Chelsea',            year: 2023, fee: 11  },
  { player: 'Bernardo Silva',      from: 'Monaco',            to: 'Manchester City',    year: 2017, fee: 43  },
  { player: 'Pepe',                from: 'Marítimo',          to: 'Porto',              year: 2004, fee: 4   },
  { player: 'Pepe',                from: 'Porto',             to: 'Real Madrid',        year: 2007, fee: 30  },
  { player: 'Ricardo Quaresma',    from: 'Barcelona',         to: 'Inter Milan',        year: 2006, fee: 18  },
  { player: 'Deco',                from: 'Porto',             to: 'Barcelona',          year: 2004, fee: 20  },
  // ── TRANSFERIMET E FUNDIT 2023-2024 ──
  { player: 'Gavi',                from: 'Barcelona',         to: 'Barcelona',          year: 2022, fee: 0   },
  { player: 'Pedri',               from: 'Barcelona',         to: 'Barcelona',          year: 2022, fee: 0   },
  { player: 'Ansu Fati',           from: 'Brighton',          to: 'Barcelona',          year: 2024, fee: 0   },
  { player: 'Sergi Roberto',       from: 'Barcelona',         to: 'AC Milan',           year: 2024, fee: 0   },
  { player: 'Nicolo Barella',      from: 'Cagliari',          to: 'Inter Milan',        year: 2020, fee: 12  },
  { player: 'Hakan Çalhanoğlu',    from: 'AC Milan',          to: 'Inter Milan',        year: 2021, fee: 0   },
  { player: 'Christian Eriksen',   from: 'Tottenham',         to: 'Inter Milan',        year: 2020, fee: 20  },
  { player: 'Christian Eriksen',   from: 'Inter Milan',       to: 'Manchester United',  year: 2022, fee: 0   },
  { player: 'Alexis Mac Allister', from: 'Brighton',          to: 'Liverpool',          year: 2023, fee: 35  },
  { player: 'Dominik Szoboszlai',  from: 'RB Leipzig',        to: 'Liverpool',          year: 2023, fee: 70  },
  { player: 'Wataru Endō',         from: 'Stuttgart',         to: 'Liverpool',          year: 2023, fee: 16  },
  { player: 'Rasmus Højlund',      from: 'Atalanta',          to: 'Manchester United',  year: 2023, fee: 72  },
  { player: 'Mason Mount',         from: 'Chelsea',           to: 'Manchester United',  year: 2023, fee: 60  },
  { player: 'André Onana',         from: 'Inter Milan',       to: 'Manchester United',  year: 2023, fee: 47  },
  { player: 'Emiliano Martínez',   from: 'Arsenal',           to: 'Aston Villa',        year: 2020, fee: 20  },
  { player: 'Ollie Watkins',       from: 'Brentford',         to: 'Aston Villa',        year: 2020, fee: 28  },
  { player: 'Jacob Ramsey',        from: 'Aston Villa',       to: 'Aston Villa',        year: 2023, fee: 0   },
  { player: 'Moussa Diaby',        from: 'Bayer Leverkusen',  to: 'Aston Villa',        year: 2023, fee: 52  },
  { player: 'Pau Torres',          from: 'Villarreal',        to: 'Aston Villa',        year: 2023, fee: 33  },
  { player: 'Youri Tielemans',     from: 'Leicester',         to: 'Aston Villa',        year: 2023, fee: 0   },
  { player: 'Amadou Onana',        from: 'Everton',           to: 'Aston Villa',        year: 2024, fee: 50  },
  { player: 'Florian Wirtz',       from: 'Bayer Leverkusen',  to: 'Bayern Munich',      year: 2025, fee: 150 },
  { player: 'Jonathan David',      from: 'Lille',             to: 'Barcelona',          year: 2025, fee: 0   },
  { player: 'Khvicha Kvaratskhelia',from: 'Napoli',           to: 'PSG',                year: 2025, fee: 70  },
  { player: 'Lamine Yamal',        from: 'La Masia',          to: 'Barcelona',          year: 2023, fee: 0   },
  { player: 'Nico Williams',       from: 'Athletic Bilbao',   to: 'Athletic Bilbao',    year: 2024, fee: 0   },
  { player: 'Federico Valverde',   from: 'Peñarol',           to: 'Real Madrid',        year: 2016, fee: 5   },
  { player: 'Aurélien Tchouaméni', from: 'Bordeaux',          to: 'Monaco',             year: 2020, fee: 18  },
  { player: 'Aurélien Tchouaméni', from: 'Monaco',            to: 'Real Madrid',        year: 2022, fee: 80  },
  { player: 'Eduardo Camavinga',   from: 'Rennes',            to: 'Real Madrid',        year: 2021, fee: 31  },
  { player: 'Éder Militão',        from: 'Porto',             to: 'Real Madrid',        year: 2019, fee: 50  },
  { player: 'Endrick',             from: 'Palmeiras',         to: 'Real Madrid',        year: 2024, fee: 60  },
  { player: 'Gonzalo Montiel',     from: 'River Plate',       to: 'Sevilla',            year: 2021, fee: 5   },
  { player: 'Marc Bartra',         from: 'Barcelona',         to: 'Dortmund',           year: 2016, fee: 8   },
  { player: 'Henrikh Mkhitaryan',  from: 'Dortmund',          to: 'Manchester United',  year: 2016, fee: 42  },
  { player: 'Henrikh Mkhitaryan',  from: 'Manchester United', to: 'Arsenal',            year: 2018, fee: 35  },
];

export function pickTransferForDate(dateStr: string): TransferRecord {
  const seed = parseInt(dateStr.replace(/-/g, ''), 10) + 7; // offset nga Career Path
  return TRANSFER_RECORDS[seed % TRANSFER_RECORDS.length];
}